// tools/builders/animals.js
module.exports = [
  // ა
  { w: "არწივი", popularity: 5, aliases: [], note: "მტაცებელი ფრინველი" },
  { w: "ავაზა", popularity: 5, aliases: ["გეპარდი"], note: "მსოფლიოში უსწრაფესი ძუძუმწოვარი" },
  { w: "ანტილოპა", popularity: 5, aliases: [], note: "ჩლიქოსანი ცხოველი" },
  { w: "არჩვი", popularity: 5, aliases: [], note: "კავკასიური მთის ცხოველი" },
  { w: "აქლემი", popularity: 5, aliases: [], note: "უდაბნოს ცხოველი" },
  { w: "აფთარი", popularity: 5, aliases: [], note: "მტაცებელი ცხოველი" },
  { w: "ალბატროსი", popularity: 4, aliases: [], note: "ოკეანის დიდი ფრინველი" },
  { w: "ალპაკა", popularity: 5, aliases: [], note: "ანდების შინაური ცხოველი" },
  { w: "ასპიტი", popularity: 4, aliases: [], note: "შხამიანი გველი" },
  { w: "აფალინა", popularity: 4, aliases: ["დელფინი"], note: "შავი ზღვის დელფინი" },
  { w: "აბრეშუმის ჭია", popularity: 4, aliases: [], note: "სასარგებლო მწერი" },
  { w: "აკულა", popularity: 4, aliases: ["ზვიგენი"], note: "მტაცებელი თევზი" },
  { w: "ალიგატორი", popularity: 5, aliases: ["ნიანგი"], note: "ქვეწარმავალი" },
  { w: "ამადინა", popularity: 3, aliases: [], note: "ჩიტუნა" },
  { w: "ანაკონდა", popularity: 5, aliases: [], note: "გიგანტური გველი" },

  // ბ
  { w: "ბუ", popularity: 5, aliases: [], note: "ღამის მტაცებელი ფრინველი" },
  { w: "ბეჰემოთი", popularity: 5, aliases: ["ჰიპოპოტამი"], note: "წყლის დიდი ძუძუმწოვარი" },
  { w: "ბატი", popularity: 5, aliases: [], note: "შინაური და გარეული ფრინველი" },
  { w: "ბაყაყი", popularity: 5, aliases: [], note: "ამფიბია" },
  { w: "ბეღურა", popularity: 5, aliases: [], note: "პატარა ქალაქური ჩიტი" },
  { w: "ბულბული", popularity: 5, aliases: [], note: "ტკბილმგალობელი ფრინველი" },
  { w: "ბოცვერი", popularity: 5, aliases: ["შინაური კურდღელი"], note: "მღრღნელი" },
  { w: "ბიზონი", popularity: 4, aliases: ["დომბა"], note: "ამერიკული გარეული ხარი" },
  { w: "ბაბუინი", popularity: 4, aliases: [], note: "მაიმუნი" },
  { w: "ბუზი", popularity: 5, aliases: [], note: "მწერი" },
  { w: "ბზიკი", popularity: 5, aliases: [], note: "მწერი" },
  { w: "ბოლოცეცხლა", popularity: 4, aliases: [], note: "ლამაზი ფრინველი" },
  { w: "ბრმაძაღლა", popularity: 3, aliases: [], note: "მიწისქვეშა ცხოველი" },
  { w: "ბურუნდუკი", popularity: 4, aliases: [], note: "ზოლებიანი ციყვი" },
  { w: "ბარაკუდა", popularity: 4, aliases: [], note: "მტაცებელი ზღვის თევზი" },
  { w: "ბელი", popularity: 4, aliases: ["დათვის შვილი"], note: "პატარა დათვი" },
  { w: "ბუღა", popularity: 5, aliases: ["ხარი"], note: "შინაური პირუტყვი" },

  // გ
  { w: "გველი", popularity: 5, aliases: [], note: "ქვეწარმავალი" },
  { w: "გედი", popularity: 5, aliases: [], note: "კეთილშობილი წყალმცურავი ფრინველი" },
  { w: "გეპარდი", popularity: 5, aliases: ["ავაზა"], note: "მსოფლიოს უსწრაფესი ცხოველი" },
  { w: "გორილა", popularity: 5, aliases: [], note: "უდიდესი პრიმატი" },
  { w: "გიბონი", popularity: 4, aliases: [], note: "პრიმატი" },
  { w: "გეკონი", popularity: 4, aliases: [], note: "ხვლიკი" },
  { w: "გარეული ღორი", popularity: 5, aliases: ["ტახი"], note: "ტყის ცხოველი" },
  { w: "გუგული", popularity: 5, aliases: [], note: "მგალობელი ფრინველი" },
  { w: "გომბეშო", popularity: 5, aliases: [], note: "ხმელეთის ამფიბია" },
  { w: "გველთევზა", popularity: 4, aliases: [], note: "გველისებრი თევზი" },
  { w: "გნუ", popularity: 4, aliases: [], note: "აფრიკული ანტილოპა" },
  { w: "გნოლი", popularity: 3, aliases: [], note: "ფრინველი" },
  { w: "გრიზლი", popularity: 5, aliases: ["რუხი დათვი"], note: "ამერიკული მურა დათვი" },
  { w: "გველხოკერა", popularity: 4, aliases: [], note: "უფეხო ხვლიკი" },

  // დ
  { w: "დათვი", popularity: 5, aliases: [], note: "ტყის დიდი მტაცებელი" },
  { w: "დელფინი", popularity: 5, aliases: [], note: "ჭკვიანი საზღვაო ძუძუმწოვარი" },
  { w: "დინგნისკარტა", popularity: 4, aliases: ["იხვნისკარტა"], note: "კვერცხისმდებელი ძუძუმწოვარი" },
  { w: "დურაჯი", popularity: 4, aliases: [], note: "ფრინველი" },
  { w: "დინგო", popularity: 4, aliases: ["ველური ძაღლი"], note: "ავსტრალიური გარეული ძაღლი" },
  { w: "დედოფალა", popularity: 4, aliases: ["სინდიოფი"], note: "პატარა მტაცებელი" },
  { w: "დრონტი", popularity: 4, aliases: ["დოდო"], note: "გადაშენებული ფრინველი" },
  { w: "დომბა", popularity: 4, aliases: ["კავკასიური ბიზონი"], note: "გარეული ხარი" },
  { w: "დუმფარას ჩიტი", popularity: 3, aliases: [], note: "ფრინველი" },
  { w: "დიკდიკი", popularity: 3, aliases: [], note: "ჯუჯა ანტილოპა" },

  // ე
  { w: "ენოტი", popularity: 5, aliases: [], note: "ზოლებიანკუდა ჭკვიანი ცხოველი" },
  { w: "ემუ", popularity: 5, aliases: [], note: "ავსტრალიური დიდი ფრინველი" },
  { w: "ექიდნა", popularity: 4, aliases: [], note: "კვერცხისმდებელი ძუძუმწოვარი" },
  { w: "ეფა", popularity: 4, aliases: [], note: "შხამიანი გველი" },
  { w: "ელანდი", popularity: 3, aliases: [], note: "დიდი ანტილოპა" },
  { w: "ეშვიანი ტახი", popularity: 4, aliases: [], note: "ცხოველი" },
  { w: "ეგრეტი", popularity: 3, aliases: ["თეთრი ყანჩა"], note: "ფრინველი" },

  // ვ
  { w: "ვეფხვი", popularity: 5, aliases: [], note: "ზოლიანი დიდი მტაცებელი კატა" },
  { w: "ვეშაპი", popularity: 5, aliases: [], note: "მსოფლიოს უდიდესი ცხოველი" },
  { w: "ვარხვი", popularity: 4, aliases: ["პელიკანი"], note: "დიდნისკარტა ფრინველი" },
  { w: "ვირი", popularity: 5, aliases: [], note: "შინაური პირუტყვი" },
  { w: "ვირთხა", popularity: 5, aliases: [], note: "მღრღნელი" },
  { w: "ვალაბი", popularity: 4, aliases: ["პატარა კენგურუ"], note: "ჩანთოსანი" },
  { w: "ვარანი", popularity: 4, aliases: ["კომოდოს დრაკონი"], note: "გიგანტური ხვლიკი" },
  { w: "ვერძი", popularity: 5, aliases: ["ცხვარი"], note: "რქიანი მამალი ცხვარი" },
  { w: "ვოლვერინი", popularity: 4, aliases: ["სასამურა", "როსომახა"], note: "მტაცებელი" },
  { w: "ვამპირი ღამურა", popularity: 4, aliases: [], note: "სისხლისმწოველი ღამურა" },

  // ზ
  { w: "ზებრა", popularity: 5, aliases: [], note: "აფრიკული ზოლებიანი ცხენი" },
  { w: "ზვიგენი", popularity: 5, aliases: ["აკულა"], note: "ზღვის საშიში მტაცებელი თევზი" },
  { w: "ზღარბი", popularity: 5, aliases: [], note: "ეკლიანი პატარა ცხოველი" },
  { w: "ზაზუნა", popularity: 5, aliases: ["ჰამსტერი"], note: "მღრღნელი" },
  { w: "ზუთხი", popularity: 5, aliases: [], note: "ძვირფასი ხიზილალიანი თევზი" },
  { w: "ზღვის ლომი", popularity: 5, aliases: [], note: "ფარფლფეხიანი ცხოველი" },
  { w: "ზღვის კატა", popularity: 4, aliases: [], note: "თევზი / სელაპი" },
  { w: "ზღვის კუ", popularity: 5, aliases: [], note: "ოკეანის დიდი ქვეწარმავალი" },
  { w: "ზღვის ცხენი", popularity: 5, aliases: [], note: "პატარა ეგზოტიკური თევზი" },
  { w: "ზღვის გოჭი", popularity: 5, aliases: [], note: "შინაური მღრღნელი" },
  { w: "ზებუ", popularity: 3, aliases: [], note: "კუზიანი ხარი" },

  // თ
  { w: "თევზი", popularity: 5, aliases: [], note: "წყლის ხერხემლიანი ბინადარი" },
  { w: "თხა", popularity: 5, aliases: [], note: "შინაური პირუტყვი" },
  { w: "თოლია", popularity: 5, aliases: [], note: "ზღვის ფრინველი" },
  { w: "თახვი", popularity: 5, aliases: [], note: "კაშხლების მშენებელი მღრღნელი" },
  { w: "თხუნელა", popularity: 5, aliases: [], note: "მიწისქვეშა მწერიჭამია" },
  { w: "თეთრი დათვი", popularity: 5, aliases: [], note: "არქტიკის მტაცებელი" },
  { w: "თეთრი ვეშაპი", popularity: 4, aliases: ["ბელუხა"], note: "პოლარული ვეშაპი" },
  { w: "თუთიყუში", popularity: 5, aliases: [], note: "მოლაპარაკე ჭრელი ფრინველი" },
  { w: "თრითინა", popularity: 4, aliases: [], note: "პატარა მღრღნელი" },
  { w: "თურა", popularity: 4, aliases: ["ტურა"], note: "მტაცებელი" },

  // ი
  { w: "ირემი", popularity: 5, aliases: [], note: "ტყის კეთილშობილი რქოსანი" },
  { w: "იხვი", popularity: 5, aliases: [], note: "წყალმცურავი ფრინველი" },
  { w: "იაგუარი", popularity: 5, aliases: [], note: "ამერიკული დიდი კატა" },
  { w: "იგუანა", popularity: 5, aliases: [], note: "ტროპიკული დიდი ხვლიკი" },
  { w: "ინდაური", popularity: 5, aliases: [], note: "შინაური დიდი ფრინველი" },
  { w: "იბისი", popularity: 4, aliases: [], note: "წმინდა ფრინველი" },
  { w: "იაკი", popularity: 4, aliases: [], note: "ტიბეტური გრძელბეწვიანი ხარი" },
  { w: "იხვნისკარტა", popularity: 5, aliases: [], note: "ავსტრალიური უნიკალური ცხოველი" },
  { w: "ივეტი", popularity: 3, aliases: [], note: "ფრინველი" },
  { w: "იმპალა", popularity: 4, aliases: [], note: "აფრიკული ანტილოპა" },

  // კ
  { w: "კატა", popularity: 5, aliases: [], note: "შინაური საყვარელი ცხოველი" },
  { w: "კუ", popularity: 5, aliases: [], note: "ჯავშნიანი ქვეწარმავალი" },
  { w: "კურდღელი", popularity: 5, aliases: [], note: "სწრაფმორბენალი გრძელყურა" },
  { w: "კენგურუ", popularity: 5, aliases: [], note: "ავსტრალიური ჩანთოსანი" },
  { w: "კოალა", popularity: 5, aliases: [], note: "ევკალიპტის მოყვარული ჩანთოსანი" },
  { w: "კოლიბრი", popularity: 5, aliases: [], note: "მსოფლიოს უმცირესი ფრინველი" },
  { w: "კობრი", popularity: 5, aliases: ["საზანი"], note: "მტკნარი წყლის თევზი" },
  { w: "კალმახი", popularity: 5, aliases: [], note: "მთის მდინარის თევზი" },
  { w: "კოდალა", popularity: 5, aliases: [], note: "ტყის მკურნალი ფრინველი" },
  { w: "კობრა", popularity: 5, aliases: [], note: "სათვალიანი შხამიანი გველი" },
  { w: "კოღო", popularity: 5, aliases: [], note: "სისხლისმწოველი მწერი" },
  { w: "კალმარი", popularity: 5, aliases: [], note: "ზღვის მოლუსკი" },
  { w: "კიბო", popularity: 5, aliases: [], note: "მდინარის ფეხსახსრიანი" },
  { w: "კიბორჩხალა", popularity: 5, aliases: ["კრაბი"], note: "ზღვის კიბო" },
  { w: "კაკაბი", popularity: 4, aliases: [], note: "მთის ფრინველი" },
  { w: "კაჭკაჭი", popularity: 5, aliases: [], note: "ჭრელი ფრინველი" },
  { w: "კაპარჭინა", popularity: 4, aliases: [], note: "თევზი" },
  { w: "კივი", popularity: 5, aliases: [], note: "ახალი ზელანდიის უფრთო ფრინველი" },
  { w: "კაშალოტი", popularity: 5, aliases: [], note: "კბილიანი გიგანტური ვეშაპი" },
  { w: "კვერნა", popularity: 4, aliases: [], note: "ტყის პატარა მტაცებელი" },

  // ლ
  { w: "ლომი", popularity: 5, aliases: [], note: "ცხოველთა მეფე" },
  { w: "ლეოპარდი", popularity: 5, aliases: ["ჯიქი"], note: "კოპლებიანი მტაცებელი კატა" },
  { w: "ლამა", popularity: 5, aliases: [], note: "სამხრეთ ამერიკული ცხოველი" },
  { w: "ლემური", popularity: 5, aliases: [], note: "მადაგასკარული პრიმატი" },
  { w: "ლურჯი ვეშაპი", popularity: 5, aliases: [], note: "დედამიწის უდიდესი ბინადარი" },
  { w: "ლოსი", popularity: 5, aliases: [], note: "ტყის გიგანტური ირემი" },
  { w: "ლემინგი", popularity: 4, aliases: [], note: "ტუნდრის პატარა მღრღნელი" },
  { w: "ლორი", popularity: 4, aliases: [], note: "ნელი პრიმატი" },
  { w: "ლაბრადორი", popularity: 4, aliases: [], note: "ძაღლის ჯიში" },
  { w: "ლეკვი", popularity: 5, aliases: [], note: "პატარა ძაღლი" },

  // მ
  { w: "მგელი", popularity: 5, aliases: [], note: "ტყის მტაცებელი" },
  { w: "მელა", popularity: 5, aliases: [], note: "ეშმაკი წითური მტაცებელი" },
  { w: "მაიმუნი", popularity: 5, aliases: [], note: "პრიმატი" },
  { w: "მტრედი", popularity: 5, aliases: [], note: "მშვიდობის სიმბოლო ფრინველი" },
  { w: "მერცხალი", popularity: 5, aliases: [], note: "გაზაფხულის მახარობელი ფრინველი" },
  { w: "მამალი", popularity: 5, aliases: [], note: "შინაური ფრინველი" },
  { w: "მაჩვი", popularity: 5, aliases: [], note: "სოროში მცხოვრები ცხოველი" },
  { w: "მორიელი", popularity: 5, aliases: [], note: "შხამიანი ფეხსახსრიანი" },
  { w: "მორჟი", popularity: 5, aliases: [], note: "ჩრდილოეთის ეშვებიანი ცხოველი" },
  { w: "მანგუსტი", popularity: 5, aliases: [], note: "გველების დამმორჩილებელი ცხოველი" },
  { w: "მუფლონი", popularity: 4, aliases: [], note: "გარეული ცხვარი" },
  { w: "მარტორქა", popularity: 5, aliases: [], note: "რქიანი დიდი ცხოველი" },
  { w: "მოლუსკი", popularity: 4, aliases: [], note: "უხერხემლო ცხოველი" },
  { w: "მედუზა", popularity: 5, aliases: [], note: "ზღვის ჟელესებრი არსება" },

  // ნ
  { w: "ნიანგი", popularity: 5, aliases: ["კროკოდილი"], note: "წყლის საშიში მტაცებელი ქვეწარმავალი" },
  { w: "ნარვალი", popularity: 5, aliases: ["ზღვის მარტორქა"], note: "რქიანი ჩრდილოეთის ვეშაპი" },
  { w: "ნუტრია", popularity: 4, aliases: [], note: "წყლის მღრღნელი" },
  { w: "ნემსიყლაპია", popularity: 5, aliases: [], note: "სწრაფმფრენი მწერი" },
  { w: "ნემსთევზა", popularity: 4, aliases: [], note: "თევზი" },
  { w: "ნუკრი", popularity: 5, aliases: ["ირმის შვილი"], note: "პატარა ირემი ან შველი" },
  { w: "ნარცისი ჩიტი", popularity: 3, aliases: [], note: "ფრინველი" },
  { w: "ნიბლია", popularity: 4, aliases: [], note: "პატარა ტყის ჩიტი" },
  { w: "ნამგალა", popularity: 4, aliases: [], note: "ფრინველი" },

  // ო
  { w: "ორაგული", popularity: 5, aliases: ["სალმონი"], note: "ძვირფასი წითელი თევზი" },
  { w: "ოფოფი", popularity: 5, aliases: [], note: "ქოჩრიანი ფრინველი" },
  { w: "ობობა", popularity: 5, aliases: [], note: "რვაფეხა მწერი/ფეხსახსრიანი" },
  { w: "ოკაპი", popularity: 4, aliases: ["ტყის ჟირაფი"], note: "აფრიკული ცხოველი" },
  { w: "ორანგუტანი", popularity: 5, aliases: [], note: "წითური დიდი მაიმუნი" },
  { w: "ორკა", popularity: 5, aliases: ["მკვლელი ვეშაპი"], note: "მტაცებელი დელფინისებრი" },
  { w: "ორბი", popularity: 5, aliases: [], note: "მაღალმთის დიდი ფრინველი" },
  { w: "ოპოსუმი", popularity: 4, aliases: [], note: "ჩანთოსანი ცხოველი" },
  { w: "ოთხთვალა თევზი", popularity: 3, aliases: [], note: "ეგზოტიკური თევზი" },
  { w: "ოქროს თევზი", popularity: 5, aliases: [], note: "აკვარიუმის თევზი" },

  // პ
  { w: "პანდა", popularity: 5, aliases: ["დიდი პანდა"], note: "ბამბუკის მოყვარული დათვი" },
  { w: "პინგვინი", popularity: 5, aliases: [], note: "ანტარქტიდის უფრენი ფრინველი" },
  { w: "პელიკანი", popularity: 5, aliases: ["ვარხვი"], note: "წყალმცურავი დიდი ფრინველი" },
  { w: "პეპელა", popularity: 5, aliases: [], note: "ფრთათეთრი ან ფერადი მწერი" },
  { w: "პითონი", popularity: 5, aliases: [], note: "დიდი მახრჩობელა გველი" },
  { w: "პუმა", popularity: 5, aliases: ["მთის ლომი"], note: "ამერიკული მტაცებელი კატა" },
  { w: "პონი", popularity: 5, aliases: [], note: "პატარა ცხენი" },
  { w: "პლატიპუსი", popularity: 4, aliases: ["იხვნისკარტა"], note: "ავსტრალიური ცხოველი" },
  { w: "პირანია", popularity: 5, aliases: [], note: "ამაზონის მტაცებელი თევზი" },
  { w: "პოლიპი", popularity: 3, aliases: [], note: "ზღვის ცხოველი" },

  // ჟ
  { w: "ჟირაფი", popularity: 5, aliases: [], note: "მსოფლიოს უმაღლესი ცხოველი" },
  { w: "ჟრუნი", popularity: 3, aliases: [], note: "პატარა ფრინველი" },
  { w: "ჟოლოჭია", popularity: 3, aliases: [], note: "მწერი" },
  { w: "ჟაკო", popularity: 4, aliases: ["რუხი თუთიყუში"], note: "მოლაპარაკე თუთიყუში" },

  // რ
  { w: "რვაფეხა", popularity: 5, aliases: ["ოქტოპუსი"], note: "ზღვის ჭკვიანი მოლუსკი" },
  { w: "რუხი მგელი", popularity: 5, aliases: [], note: "ტყის მტაცებელი" },
  { w: "რუხი დათვი", popularity: 5, aliases: ["გრიზლი"], note: "მტაცებელი" },
  { w: "რქოსანი ხოჭო", popularity: 4, aliases: [], note: "მწერი" },
  { w: "რემორა", popularity: 3, aliases: ["მიმკვრელი თევზი"], note: "თევზი" },
  { w: "რუხი ყანჩა", popularity: 4, aliases: [], note: "ფრინველი" },

  // ს
  { w: "სპილო", popularity: 5, aliases: [], note: "ხმელეთის უდიდესი ცხოველი ხორთუმით" },
  { w: "სირაქლემა", popularity: 5, aliases: [], note: "მსოფლიოს უდიდესი ფრინველი" },
  { w: "სელაპი", popularity: 5, aliases: [], note: "ზღვის ძუძუმწოვარი" },
  { w: "სკუნსი", popularity: 5, aliases: [], note: "თავდაცვითი სუნის მქონე ცხოველი" },
  { w: "სვავი", popularity: 5, aliases: [], note: "მძორისმჭამელი დიდი ფრინველი" },
  { w: "სიასამური", popularity: 4, aliases: ["სამური"], note: "ძვირფასბეწვიანი მტაცებელი" },
  { w: "სკუმბრია", popularity: 5, aliases: [], note: "ზღვის სარეწაო თევზი" },
  { w: "სარდინი", popularity: 5, aliases: [], note: "პატარა ზღვის თევზი" },
  { w: "სკაროსი", popularity: 4, aliases: [], note: "ბრტყელი ზღვის თევზი" },
  { w: "სინდიოფი", popularity: 4, aliases: ["დედოფალა"], note: "პატარა მტაცებელი" },
  { w: "სვინცი", popularity: 3, aliases: [], note: "თევზი" },

  // ტ
  { w: "ტურა", popularity: 5, aliases: [], note: "მტაცებელი ცხოველი" },
  { w: "ტახი", popularity: 5, aliases: ["გარეული ღორი"], note: "ტყის ცხოველი" },
  { w: "ტარაკანი", popularity: 5, aliases: [], note: "გამძლე მწერი" },
  { w: "ტარანტული", popularity: 5, aliases: [], note: "დიდი შხამიანი ობობა" },
  { w: "ტილი", popularity: 4, aliases: [], note: "პარაზიტი მწერი" },
  { w: "ტაიპანი", popularity: 4, aliases: [], note: "მსოფლიოში ყველაზე შხამიანი გველი" },
  { w: "ტერმიტი", popularity: 4, aliases: [], note: "ხის მჭამელი მწერი" },
  { w: "ტოროლა", popularity: 5, aliases: [], note: "მგალობელი მინდვრის ჩიტი" },
  { w: "ტრიტონი", popularity: 4, aliases: [], note: "კუდიანი ამფიბია" },
  { w: "ტუნა", popularity: 5, aliases: ["თინუსი"], note: "ოკეანის დიდი თევზი" },
  { w: "ტაპირი", popularity: 4, aliases: [], note: "ტროპიკული ცხოველი" },

  // უ
  { w: "უსურიული ვეფხვი", popularity: 5, aliases: ["ამურის ვეფხვი"], note: "ყველაზე დიდი კატა" },
  { w: "უშნო იხვი", popularity: 4, aliases: [], note: "ფრინველი" },
  { w: "უნაგირიანი დელფინი", popularity: 3, aliases: [], note: "ზღვის ცხოველი" },
  { w: "უდაბნოს მელა", popularity: 4, aliases: ["ფენეკი"], note: "დიდყურა მელა" },
  { w: "უკუდო მაიმუნი", popularity: 4, aliases: [], note: "პრიმატი" },
  { w: "ურიალი", popularity: 3, aliases: [], note: "გარეული ცხვარი" },

  // ფ
  { w: "ფოცხვერი", popularity: 5, aliases: [], note: "ყურებზე ფუნჯებიანი ტყის კატა" },
  { w: "ფარშავანგი", popularity: 5, aliases: [], note: "ულამაზესკუდიანი ფრინველი" },
  { w: "ფლამინგო", popularity: 5, aliases: [], note: "ვარდისფერი გრძელფეხა ფრინველი" },
  { w: "ფუტკარი", popularity: 5, aliases: [], note: "თაფლის მომცემი მწერი" },
  { w: "ფასკუნჯი", popularity: 4, aliases: [], note: "მტაცებელი ფრინველი" },
  { w: "ფრინველი", popularity: 5, aliases: [], note: "ფრთოსანი არსება" },
  { w: "ფლუნდერი", popularity: 4, aliases: ["კამბალა"], note: "ბრტყელი თევზი" },
  { w: "ფენეკი", popularity: 4, aliases: ["უდაბნოს მელა"], note: "პატარა ცხოველი" },
  { w: "ფერისკოკერი", popularity: 3, aliases: [], note: "ფრინველი" },

  // ქ
  { w: "ქორი", popularity: 5, aliases: [], note: "სწრაფი მტაცებელი ფრინველი" },
  { w: "ქათამი", popularity: 5, aliases: [], note: "ყველაზე გავრცელებული შინაური ფრინველი" },
  { w: "ქაშაპი", popularity: 4, aliases: [], note: "მდინარის თევზი" },
  { w: "ქამელეონი", popularity: 5, aliases: [], note: "ფერშეცვლადი ქვეწარმავალი" },
  { w: "ქორიყლაპია", popularity: 3, aliases: [], note: "ჩიტი" },
  { w: "ქრცვინი", popularity: 4, aliases: ["ყარყუმი"], note: "პატარა თეთრი მტაცებელი" },
  { w: "ქერჩლიანი ხვლიკი", popularity: 3, aliases: [], note: "ქვეწარმავალი" },

  // ღ
  { w: "ღორი", popularity: 5, aliases: [], note: "შინაური პირუტყვი" },
  { w: "ღამურა", popularity: 5, aliases: [], note: "მფრინავი ძუძუმწოვარი" },
  { w: "ღრიანკალი", popularity: 5, aliases: ["მორიელი"], note: "ფეხსახსრიანი" },
  { w: "ღორთევზა", popularity: 3, aliases: [], note: "თევზი" },
  { w: "ღვთის ჩიტი", popularity: 4, aliases: ["ჭიამაია"], note: "წითელი წინწკლებიანი მწერი" },

  // ყ
  { w: "ყვავი", popularity: 5, aliases: [], note: "ჭკვიანი შავი ფრინველი" },
  { w: "ყანჩა", popularity: 5, aliases: [], note: "ჭაობის გრძელფეხა ფრინველი" },
  { w: "ყარყუმი", popularity: 5, aliases: [], note: "თეთრბეწვიანი პატარა მტაცებელი" },
  { w: "ყარყატი", popularity: 5, aliases: ["წერო"], note: "ფრინველი" },
  { w: "ყვითელმუცელა გველი", popularity: 3, aliases: [], note: "ქვეწარმავალი" },
  { w: "ყურშა", popularity: 4, aliases: [], note: "მითოლოგიური ერთგული ძაღლი" },

  // შ
  { w: "შველი", popularity: 5, aliases: [], note: "ტყის მოხდენილი ჩლიქოსანი" },
  { w: "შაშვი", popularity: 5, aliases: [], note: "მგალობელი ტყის ფრინველი" },
  { w: "შიმპანზე", popularity: 5, aliases: [], note: "ადამიანის უახლოესი ნათესავი მაიმუნი" },
  { w: "შავარდენი", popularity: 5, aliases: [], note: "უსწრაფესი მტაცებელი ფრინველი" },
  { w: "შავი ავაზა", popularity: 5, aliases: ["პანტერა"], note: "მტაცებელი კატა" },
  { w: "შავი გედი", popularity: 4, aliases: [], note: "იშვიათი ავსტრალიური ფრინველი" },
  { w: "შაკალი", popularity: 4, aliases: ["ტურა"], note: "მტაცებელი" },
  { w: "შინაური იხვი", popularity: 4, aliases: [], note: "ფრინველი" },

  // ჩ
  { w: "ჩიტუნა", popularity: 5, aliases: ["ჩიტი"], note: "პატარა ფრინველი" },
  { w: "ჩხიკვი", popularity: 5, aliases: [], note: "ტყის ხმაურიანი ფრინველი" },
  { w: "ჩხრიალა გველი", popularity: 5, aliases: [], note: "კუდზე ე.წ. ჩხრიალით აღჭურვილი გველი" },
  { w: "ჩინჩილა", popularity: 5, aliases: [], note: "რბილბეწვიანი მთის მღრღნელი" },
  { w: "ჩანთოსანი დათვი", popularity: 4, aliases: ["კოალა"], note: "ავსტრალიური ცხოველი" },
  { w: "ჩაფხუტოსანი კაზუარი", popularity: 3, aliases: [], note: "საშიში ფრინველი" },

  // ც
  { w: "ციყვი", popularity: 5, aliases: [], note: "ხეებზე მცხოვრები კაკლის მოყვარული მღრღნელი" },
  { w: "ცხვარი", popularity: 5, aliases: [], note: "შინაური მატყლოვანი პირუტყვი" },
  { w: "ცხენი", popularity: 5, aliases: [], note: "ერთგული შინაური ცხოველი" },
  { w: "ციცარი", popularity: 4, aliases: [], note: "შინაური ფრინველი" },
  { w: "ციცინათელა", popularity: 5, aliases: [], note: "ღამით მანათობელი მწერი" },
  { w: "ცისფერი ვეშაპი", popularity: 5, aliases: [], note: "გიგანტური ოკეანური ცხოველი" },
  { w: "ცხვირრქოსანი", popularity: 4, aliases: ["მარტორქა"], note: "ცხოველი" },

  // ძ
  { w: "ძაღლი", popularity: 5, aliases: [], note: "ადამიანის საუკეთესო მეგობარი" },
  { w: "ძროხა", popularity: 5, aliases: [], note: "შინაური რძის მომცემი პირუტყვი" },
  { w: "ძერა", popularity: 5, aliases: [], note: "მტაცებელი ფრინველი" },
  { w: "ძილგუდა", popularity: 4, aliases: [], note: "მძინარა პატარა მღრღნელი" },
  { w: "ძუძუმწოვარი", popularity: 4, aliases: [], note: "ცხოველთა კლასი" },

  // წ
  { w: "წავი", popularity: 5, aliases: [], note: "წყლის მოხერხებული მტაცებელი" },
  { w: "წერო", popularity: 5, aliases: [], note: "გადამფრენი გრძელფეხა ფრინველი" },
  { w: "წიწილა", popularity: 5, aliases: ["ქათმის შვილი"], note: "პატარა ფრინველი" },
  { w: "წურბელა", popularity: 5, aliases: [], note: "წყლის ჭია" },
  { w: "წვერა", popularity: 4, aliases: [], note: "მდინარის თევზი" },
  { w: "წითელი მელა", popularity: 5, aliases: [], note: "მტაცებელი" },
  { w: "წრიპინა", popularity: 3, aliases: [], note: "ჩიტი" },

  // ჭ
  { w: "ჭიანჭველა", popularity: 5, aliases: [], note: "მშრომელი პატარა მწერი" },
  { w: "ჭრიჭინა", popularity: 5, aliases: [], note: "ზაფხულის ხმაურიანი მწერი" },
  { w: "ჭიამაია", popularity: 5, aliases: ["ღვთის ჩიტი"], note: "წინწკლებიანი წითელი მწერი" },
  { w: "ჭოტი", popularity: 5, aliases: ["პატარა ბუ"], note: "ღამის ფრინველი" },
  { w: "ჭიაყელა", popularity: 5, aliases: ["მიწის ჭია"], note: "უხერხემლო" },
  { w: "ჭიანჭველაჭამია", popularity: 5, aliases: [], note: "გრძელცხვირა ცხოველი" },
  { w: "ჭაობის კუ", popularity: 4, aliases: [], note: "ქვეწარმავალი" },

  // ხ
  { w: "ხოხობი", popularity: 5, aliases: [], note: "თბილისის ლეგენდის ფრინველი" },
  { w: "ხვლიკი", popularity: 5, aliases: [], note: "მოქნილი ქვეწარმავალი" },
  { w: "ხარი", popularity: 5, aliases: [], note: "შინაური პირუტყვი" },
  { w: "ხოჭო", popularity: 5, aliases: [], note: "მყარფრთიანი მწერი" },
  { w: "ხამანწკა", popularity: 5, aliases: ["ოსტრიცა"], note: "ზღვის ნიჟარიანი მოლუსკი" },
  { w: "ხმალთევზა", popularity: 5, aliases: [], note: "ხმლისებრნისკარტიანი სწრაფი თევზი" },
  { w: "ხალიანი ირემი", popularity: 4, aliases: [], note: "ირემი" },
  { w: "ხოჭო-ირემა", popularity: 4, aliases: ["რქოსანი ხოჭო"], note: "მწერი" },

  // ჯ
  { w: "ჯიხვი", popularity: 5, aliases: [], note: "კავკასიონის მთის კეთილშობილი თხა" },
  { w: "ჯეირანი", popularity: 5, aliases: ["ქურციკი"], note: "მოხდენილი ანტილოპა" },
  { w: "ჯორი", popularity: 5, aliases: [], note: "ცხენისა და ვირის ნაჯვარი" },
  { w: "ჯიქი", popularity: 5, aliases: ["ლეოპარდი"], note: "კავკასიური ლეოპარდი" },
  { w: "ჯუჯა პანდა", popularity: 4, aliases: ["წითელი პანდა"], note: "ცხოველი" },
  { w: "ჯუჯა ბეჰემოთი", popularity: 4, aliases: [], note: "ცხოველი" },

  // ჰ
  { w: "ჰიენა", popularity: 5, aliases: ["აფთარი"], note: "აფრიკული მტაცებელი" },
  { w: "ჰიპოპოტამი", popularity: 5, aliases: ["ბეჰემოთი"], note: "დიდი წყლის ცხოველი" },
  { w: "ჰამადრილი", popularity: 4, aliases: ["პავიანი"], note: "მაიმუნი" },
  { w: "ჰამსტერი", popularity: 4, aliases: ["ზაზუნა"], note: "მღრღნელი" },
  { w: "ჰალიბუტი", popularity: 4, aliases: [], note: "ოკეანის დიდი თევზი" },
  { w: "ჰერმელინი", popularity: 4, aliases: ["ყარყუმი"], note: "პატარა მტაცებელი" }
];
