// tools/builders/geography.js
module.exports = [
  // ა
  { w: "ალაზანი", popularity: 5, aliases: [], note: "მდინარე აღმოსავლეთ საქართველოში" },
  { w: "არაგვი", popularity: 5, aliases: [], note: "მდინარე საქართველოში" },
  { w: "აბაშა", popularity: 4, aliases: [], note: "მდინარე სამეგრელოში" },
  { w: "ალპები", popularity: 5, aliases: [], note: "მთათა სისტემა ევროპაში" },
  { w: "ამაზონი", popularity: 5, aliases: [], note: "მსოფლიოში ყველაზე წყალუხვი მდინარე" },
  { w: "ატლანტის ოკეანე", popularity: 5, aliases: ["ატლანტიკა"], note: "დიდი ოკეანე" },
  { w: "ანდები", popularity: 5, aliases: [], note: "მთათა სისტემა სამხრეთ ამერიკაში" },
  { w: "არალის ზღვა", popularity: 4, aliases: [], note: "ტბა ცენტრალურ აზიაში" },
  { w: "აფშერონი", popularity: 3, aliases: [], note: "ნახევარკუნძული" },
  { w: "აპალაჩები", popularity: 4, aliases: [], note: "მთები ჩრდილოეთ ამერიკაში" },
  { w: "ალასკა", popularity: 4, aliases: [], note: "ნახევარკუნძული" },
  { w: "აზოვის ზღვა", popularity: 4, aliases: [], note: "ზღვა ევროპაში" },
  { w: "აბული", popularity: 4, aliases: ["დიდი აბული"], note: "მთა ჯავახეთში" },
  { w: "აილამა", popularity: 4, aliases: [], note: "მწვერვალი სვანეთში" },
  { w: "არარატი", popularity: 5, aliases: ["მასისი"], note: "ვულკანური მთა" },
  { w: "არდენი", popularity: 3, aliases: [], note: "მთები ევროპაში" },
  { w: "ადრიატიკის ზღვა", popularity: 5, aliases: [], note: "ზღვა იტალიასა და ბალკანეთს შორის" },
  { w: "ეგეოსის ზღვა", popularity: 5, aliases: [], note: "ზღვა საბერძნეთთან" },
  { w: "ამურ-დარია", popularity: 4, aliases: ["ამუდარია"], note: "მდინარე აზიაში" },
  { w: "ამური", popularity: 4, aliases: [], note: "მდინარე შორეულ აღმოსავლეთში" },

  // ბ
  { w: "ბზიფი", popularity: 5, aliases: [], note: "მდინარე აფხაზეთში" },
  { w: "ბაზალეთის ტბა", popularity: 5, aliases: ["ბაზალეთი"], note: "ტბა აღმოსავლეთ საქართველოში" },
  { w: "ბაიკალი", popularity: 5, aliases: [], note: "მსოფლიოს უღრმესი ტბა" },
  { w: "ბალტიის ზღვა", popularity: 5, aliases: [], note: "ზღვა ჩრდილოეთ ევროპაში" },
  { w: "ბარენცის ზღვა", popularity: 4, aliases: [], note: "ჩრდილოეთის ზღვა" },
  { w: "ბოსფორი", popularity: 5, aliases: [], note: "სრუტე სტამბოლთან" },
  { w: "ბერინგის სრუტე", popularity: 5, aliases: [], note: "სრუტე აზიასა და ამერიკას შორის" },
  { w: "ბენგალის ყურე", popularity: 4, aliases: [], note: "ყურე ინდოეთის ოკეანეში" },
  { w: "ბორბალო", popularity: 4, aliases: [], note: "მთა კავკასიონზე" },
  { w: "ბალხაში", popularity: 4, aliases: [], note: "ნახევრად მარილიანი ტბა ყაზახეთში" },
  { w: "ბისკაიის ყურე", popularity: 4, aliases: [], note: "ყურე ატლანტის ოკეანეში" },
  { w: "ბრაჰმაპუტრა", popularity: 4, aliases: [], note: "მდინარე აზიაში" },
  { w: "ბეშუმი", popularity: 4, aliases: [], note: "მთის კურორტი აჭარაში" },
  { w: "ბაკურიანი", popularity: 4, aliases: [], note: "მთა / კურორტი" },
  { w: "ბაკოს ყურე", popularity: 3, aliases: [], note: "გეოგრაფიული ობიექტი" },

  // გ
  { w: "გუდაურის უღელტეხილი", popularity: 4, aliases: ["გუდაური", "ჯვრის უღელტეხილი"], note: "უღელტეხილი კავკასიონზე" },
  { w: "გოდერძის უღელტეხილი", popularity: 4, aliases: ["გოდერძი"], note: "უღელტეხილი არსიანის ქედზე" },
  { w: "განგი", popularity: 5, aliases: [], note: "ინდოეთის წმინდა მდინარე" },
  { w: "გიბრალტარის სრუტე", popularity: 5, aliases: ["გიბრალტარი"], note: "სრუტე ატლანტიკასა და ხმელთაშუა ზღვას შორის" },
  { w: "გობის უდაბნო", popularity: 5, aliases: ["გობი"], note: "უდაბნო ცენტრალურ აზიაში" },
  { w: "გოლფსტრიმი", popularity: 5, aliases: [], note: "თბილი ოკეანური დინება" },
  { w: "გუდის ყურე", popularity: 3, aliases: [], note: "ობიექტი" },
  { w: "გრენლანდია", popularity: 5, aliases: [], note: "მსოფლიოს უდიდესი კუნძული" },
  { w: "გუჯარეთისწყალი", popularity: 3, aliases: [], note: "მდინარე ბორჯომში" },
  { w: "გალაპაგოსის კუნძულები", popularity: 5, aliases: ["გალაპაგოსი"], note: "კუნძულები წყნარ ოკეანეში" },
  { w: "დიდი კანიონი", popularity: 5, aliases: [], note: "კანიონი აშშ-ში" },

  // დ
  { w: "დუნაი", popularity: 5, aliases: [], note: "ევროპის მეორე უგრძესი მდინარე" },
  { w: "დნეპრი", popularity: 5, aliases: ["დნიპრო"], note: "მდინარე უკრაინაში" },
  { w: "დონი", popularity: 5, aliases: [], note: "მდინარე აღმოსავლეთ ევროპაში" },
  { w: "დნესტრი", popularity: 4, aliases: [], note: "მდინარე მოლდოვასა და უკრაინაში" },
  { w: "დიკლო", popularity: 4, aliases: [], note: "მწვერვალი თუშეთში" },
  { w: "დარდანელის სრუტე", popularity: 5, aliases: ["დარდანელი"], note: "სრუტე თურქეთში" },
  { w: "დარიალის ხეობა", popularity: 5, aliases: ["დარიალი"], note: "ხეობა თერგზე" },
  { w: "დიდი ბარიერული რიფი", popularity: 5, aliases: [], note: "მარჯნის რიფი ავსტრალიასთან" },
  { w: "დევიკოლი", popularity: 3, aliases: [], note: "ტბა" },
  { w: "დიდი ტბები", popularity: 5, aliases: [], note: "ტბათა სისტემა ჩრდილოეთ ამერიკაში" },

  // ე
  { w: "ენგური", popularity: 5, aliases: [], note: "უდიდესი ჰიდროელექტროსადგურის მდინარე საქართველოში" },
  { w: "ევერესტი", popularity: 5, aliases: ["ჯომოლუნგმა"], note: "მსოფლიოს უმაღლესი მწვერვალი" },
  { w: "ევფრატი", popularity: 5, aliases: [], note: "ისტორიული მდინარე მესოპოტამიაში" },
  { w: "ელბა", popularity: 4, aliases: [], note: "მდინარე გერმანიაში" },
  { w: "ელბრუსი", popularity: 5, aliases: ["იალბუზი"], note: "კავკასიონის უმაღლესი მწვერვალი" },
  { w: "ეტნა", popularity: 5, aliases: [], note: "მოქმედი ვულკანი სიცილიაზე" },
  { w: "ერი", popularity: 4, aliases: ["ერის ტბა"], note: "დიდი ტბა ამერიკაში" },
  { w: "ევერგლეიდსი", popularity: 3, aliases: [], note: "ჭაობი ფლორიდაში" },

  // ვ
  { w: "ვოლგა", popularity: 5, aliases: [], note: "ევროპის უგრძესი მდინარე" },
  { w: "ვეზუვი", popularity: 5, aliases: [], note: "მოქმედი ვულკანი იტალიაში" },
  { w: "ვიქტორია", popularity: 5, aliases: ["ვიქტორიას ტბა", "ვიქტორიას ჩანჩქერი"], note: "აფრიკის უდიდესი ტბა და ჩანჩქერი" },
  { w: "ვისლა", popularity: 4, aliases: [], note: "მდინარე პოლონეთში" },
  { w: "ვანის ტბა", popularity: 4, aliases: ["ვანი"], note: "მარილიანი ტბა თურქეთში" },
  { w: "ვალიადოლიდის ველი", popularity: 3, aliases: [], note: "ველი" },
  { w: "ვორონია", popularity: 4, aliases: ["კრუბერის გამოქვაბული"], note: "მსოფლიოს ერთ-ერთი უღრმესი მღვიმე აფხაზეთში" },

  // ზ
  { w: "ზეკარის უღელტეხილი", popularity: 4, aliases: ["ზეკარი"], note: "უღელტეხილი მესხეთის ქედზე" },
  { w: "ზამბეზი", popularity: 5, aliases: [], note: "მდინარე აფრიკაში ჩანჩქერ ვიქტორიით" },
  { w: "ზონდის სრუტე", popularity: 3, aliases: [], note: "სრუტე ინდონეზიაში" },
  { w: "ზაგროსი", popularity: 4, aliases: [], note: "მთათა სისტემა ირანში" },
  { w: "ზღვისპირა ქედი", popularity: 3, aliases: [], note: "ქედი" },
  { w: "ზაირის მდინარე", popularity: 4, aliases: ["კონგო"], note: "მდინარე აფრიკაში" },

  // თ
  { w: "თერგი", popularity: 5, aliases: [], note: "მდინარე კავკასიაში, ხევში" },
  { w: "თეთნულდი", popularity: 5, aliases: [], note: "თეთრი მწვერვალი სვანეთში" },
  { w: "თებულო", popularity: 4, aliases: [], note: "აღმოსავლეთ კავკასიონის უმაღლესი მთა" },
  { w: "თბილისის ზღვა", popularity: 5, aliases: ["თბილისის წყალსაცავი"], note: "წყალსაცავი თბილისში" },
  { w: "თემზა", popularity: 5, aliases: [], note: "მდინარე ლონდონში" },
  { w: "თირი", popularity: 3, aliases: [], note: "სრუტე" },
  { w: "თიან-შანი", popularity: 5, aliases: [], note: "მთათა სისტემა ცენტრალურ აზიაში" },
  { w: "თარის უდაბნო", popularity: 4, aliases: [], note: "უდაბნო ინდოეთსა და პაკისტანში" },
  { w: "ტიბრი", popularity: 4, aliases: [], note: "მდინარე რომში" },

  // ი
  { w: "იორი", popularity: 5, aliases: [], note: "მდინარე კახეთში" },
  { w: "ინდოეთის ოკეანე", popularity: 5, aliases: [], note: "მსოფლიოს მესამე ოკეანე" },
  { w: "ინდი", popularity: 5, aliases: [], note: "დიდი მდინარე სამხრეთ აზიაში" },
  { w: "იენისეი", popularity: 5, aliases: [], note: "დიდი მდინარე ციმბირში" },
  { w: "ირტიში", popularity: 4, aliases: [], note: "მდინარე აზიაში" },
  { w: "იანძი", popularity: 5, aliases: [], note: "აზიის უგრძესი მდინარე" },
  { w: "იგუასუ", popularity: 5, aliases: ["იგუასუს ჩანჩქერი"], note: "ჩანჩქერი სამხრეთ ამერიკაში" },
  { w: "ისლანდიის ვულკანები", popularity: 4, aliases: [], note: "ვულკანური რეგიონი" },
  { w: "იურის მთები", popularity: 3, aliases: ["იურა"], note: "მთები ევროპაში" },
  { w: "ილმენის ტბა", popularity: 3, aliases: [], note: "ტბა რუსეთში" },

  // კ
  { w: "კოდორი", popularity: 5, aliases: [], note: "მდინარე აფხაზეთში" },
  { w: "კასპიის ზღვა", popularity: 5, aliases: [], note: "მსოფლიოს უდიდესი ტბა" },
  { w: "კავკასიონი", popularity: 5, aliases: ["კავკასიის მთები"], note: "მთათა სისტემა საქართველოს ჩრდილოეთით" },
  { w: "კილიმანჯარო", popularity: 5, aliases: [], note: "აფრიკის უმაღლესი მთა" },
  { w: "კოლორადო", popularity: 5, aliases: ["მდინარე კოლორადო"], note: "მდინარე ჩრდილოეთ ამერიკაში" },
  { w: "კონგო", popularity: 5, aliases: [], note: "მდინარე აფრიკაში" },
  { w: "კარიბის ზღვა", popularity: 5, aliases: [], note: "ტროპიკული ზღვა ამერიკაში" },
  { w: "კუს ტბა", popularity: 5, aliases: [], note: "ტბა თბილისში" },
  { w: "კორდილიერები", popularity: 5, aliases: [], note: "მთათა გიგანტური სისტემა" },
  { w: "კარპატები", popularity: 5, aliases: [], note: "მთები ცენტრალურ და აღმოსავლეთ ევროპაში" },
  { w: "კალახარი", popularity: 4, aliases: ["კალაჰარი"], note: "უდაბნო სამხრეთ აფრიკაში" },
  { w: "კრაკატაუ", popularity: 4, aliases: [], note: "ცნობილი ვულკანი ინდონეზიაში" },
  { w: "კურილის კუნძულები", popularity: 4, aliases: [], note: "არქიპელაგი წყნარ ოკეანეში" },
  { w: "კიჟი", popularity: 3, aliases: [], note: "კუნძული ონეგის ტბაზე" },

  // ლ
  { w: "ლიახვი", popularity: 5, aliases: ["დიდი ლიახვი"], note: "მდინარე შიდა ქართლში" },
  { w: "ლისის ტბა", popularity: 5, aliases: [], note: "ტბა თბილისში" },
  { w: "ლადოგის ტბა", popularity: 5, aliases: ["ლადოგი"], note: "ევროპის უდიდესი ტბა" },
  { w: "ლენა", popularity: 5, aliases: [], note: "მდინარე ციმბირში" },
  { w: "ლოხ-ნესი", popularity: 5, aliases: [], note: "ტბა შოტლანდიაში" },
  { w: "ლუარა", popularity: 4, aliases: [], note: "მდინარე საფრანგეთში" },
  { w: "ლა-მანში", popularity: 5, aliases: ["ინგლისის არხი"], note: "სრუტე ბრიტანეთსა და საფრანგეთს შორის" },
  { w: "ლოპოტა", popularity: 5, aliases: ["ლოპოტის ტბა"], note: "ტბა კახეთში" },
  { w: "ლაპტევების ზღვა", popularity: 4, aliases: [], note: "ჩრდილოეთის ყინულოვანი ზღვა" },
  { w: "ლებარდე", popularity: 4, aliases: [], note: "კურორტი და ხეობა სამეგრელოში" },

  // მ
  { w: "მტკვარი", popularity: 5, aliases: [], note: "საქართველოს უმთავრესი მდინარე" },
  { w: "მყინვარწვერი", popularity: 5, aliases: ["ყაზბეგი"], note: "მთა კავკასიონზე" },
  { w: "მისისიპი", popularity: 5, aliases: [], note: "ჩრდილოეთ ამერიკის უდიდესი მდინარე" },
  { w: "მისური", popularity: 4, aliases: [], note: "მდინარე აშშ-ში" },
  { w: "მარიანას ღრმული", popularity: 5, aliases: [], note: "ოკეანის უღრმესი ადგილი" },
  { w: "მკვდარი ზღვა", popularity: 5, aliases: [], note: "მსოფლიოში ყველაზე მარილიანი ტბა" },
  { w: "მონბლანი", popularity: 5, aliases: [], note: "ალპების უმაღლესი მწვერვალი" },
  { w: "მექსიკის ყურე", popularity: 5, aliases: [], note: "დიდი ყურე ატლანტიკაში" },
  { w: "მაშავერა", popularity: 4, aliases: [], note: "მდინარე ქვემო ქართლში" },
  { w: "მადაგასკარი", popularity: 5, aliases: [], note: "კუნძული ინდოეთის ოკეანეში" },
  { w: "მაგელანის სრუტე", popularity: 5, aliases: [], note: "სრუტე სამხრეთ ამერიკის კიდეზე" },
  { w: "მელანეზია", popularity: 3, aliases: [], note: "კუნძულოვანი რეგიონი" },

  // ნ
  { w: "ნილოსი", popularity: 5, aliases: [], note: "მსოფლიოს უგრძესი მდინარე" },
  { w: "ნიაგარა", popularity: 5, aliases: ["ნიაგარის ჩანჩქერი"], note: "ჩანჩქერი აშშ-კანადის საზღვარზე" },
  { w: "ნორილსკი", popularity: 3, aliases: [], note: "პოლარული მხარე" },
  { w: "ნამიბის უდაბნო", popularity: 4, aliases: ["ნამიბი"], note: "უძველესი უდაბნო აფრიკაში" },
  { w: "ნორვეგიის ზღვა", popularity: 4, aliases: [], note: "ატლანტის ზღვა" },
  { w: "ნიგერი", popularity: 4, aliases: [], note: "დიდი მდინარე დასავლეთ აფრიკაში" },
  { w: "ნოსოროგი", popularity: 3, aliases: [], note: "კონცხი" },
  { w: "ნეკარი", popularity: 3, aliases: [], note: "მდინარე გერმანიაში" },

  // ო
  { w: "ობი", popularity: 5, aliases: [], note: "გიგანტური მდინარე ციმბირში" },
  { w: "ონიგო", popularity: 3, aliases: [], note: "ტბა" },
  { w: "ონეგის ტბა", popularity: 4, aliases: ["ონეგა"], note: "ტბა რუსეთში" },
  { w: "ონტარიო", popularity: 5, aliases: ["ონტარიოს ტბა"], note: "დიდი ტბა ჩრდილოეთ ამერიკაში" },
  { w: "ოკა", popularity: 4, aliases: [], note: "მდინარე რუსეთში ვოლგის შენაკადი" },
  { w: "ორინოკო", popularity: 4, aliases: [], note: "მდინარე სამხრეთ ამერიკაში" },
  { w: "ოხოტის ზღვა", popularity: 4, aliases: [], note: "ზღვა წყნარ ოკეანეში" },
  { w: "ოძრხე", popularity: 3, aliases: [], note: "ისტორიული გეოგრაფიული პუნქტი" },

  // პ
  { w: "პალიასტომი", popularity: 5, aliases: ["პალიასტომის ტბა"], note: "ტბა კოლხეთის დაბლობზე" },
  { w: "წყნარი ოკეანე", popularity: 5, aliases: [], note: "დედამიწის უდიდესი ოკეანე" },
  { w: "პანამის არხი", popularity: 5, aliases: [], note: "საზღვაო არხი ორ ოკეანეს შორის" },
  { w: "პირენეები", popularity: 5, aliases: [], note: "მთები ესპანეთსა და საფრანგეთს შორის" },
  { w: "პამირი", popularity: 5, aliases: ["მსოფლიოს სახურავი"], note: "მაღალმთიანი სისტემა აზიაში" },
  { w: "პო", popularity: 4, aliases: [], note: "უდიდესი მდინარე იტალიაში" },
  { w: "პოტამოსი", popularity: 3, aliases: [], note: "მდინარე" },
  { w: "პარანა", popularity: 4, aliases: [], note: "დიდი მდინარე სამხრეთ ამერიკაში" },

  // ჟ
  { w: "ჟინვალის წყალსაცავი", popularity: 5, aliases: ["ჟინვალი"], note: "წყალსაცავი არაგვზე" },
  { w: "ჟაბლიაკი", popularity: 3, aliases: [], note: "დურმიტორის მთიანი რეგიონი" },
  { w: "ჟუჟოუ", popularity: 2, aliases: [], note: "ხეობა" },

  // რ
  { w: "რიონი", popularity: 5, aliases: [], note: "დასავლეთ საქართველოს უდიდესი მდინარე" },
  { w: "რაინი", popularity: 5, aliases: [], note: "ევროპის მნიშვნელოვანი სამდინარო გზა" },
  { w: "რიწის ტბა", popularity: 5, aliases: ["რიწა"], note: "ულამაზესი მაღალმთიანი ტბა აფხაზეთში" },
  { w: "რონა", popularity: 4, aliases: [], note: "მდინარე საფრანგეთსა და შვეიცარიაში" },
  { w: "რიკოთის უღელტეხილი", popularity: 5, aliases: ["რიკოთი"], note: "უღელტეხილი აღმოსავლეთ და დასავლეთ საქართველოს შორის" },
  { w: "როკის უღელტეხილი", popularity: 4, aliases: ["როკი"], note: "უღელტეხილი კავკასიონზე" },
  { w: "რუბიკონი", popularity: 4, aliases: [], note: "ისტორიული მდინარე იტალიაში" },
  { w: "რუსთაველის მწვერვალი", popularity: 4, aliases: [], note: "მწვერვალი კავკასიონზე" },

  // ს
  { w: "სუფსა", popularity: 5, aliases: [], note: "მდინარე გურიაში" },
  { w: "სამსარი", popularity: 4, aliases: [], note: "ვულკანური ქედი და მწვერვალი ჯავახეთში" },
  { w: "სიონის წყალსაცავი", popularity: 4, aliases: ["სიონი"], note: "წყალსაცავი იორზე" },
  { w: "საჰარა", popularity: 5, aliases: ["საჰარის უდაბნო"], note: "მსოფლიოს უდიდესი ცხელი უდაბნო" },
  { w: "სუეცის არხი", popularity: 5, aliases: [], note: "საზღვაო არხი წითელ და ხმელთაშუა ზღვებს შორის" },
  { w: "სენ-გოთარდი", popularity: 4, aliases: [], note: "ალპური უღელტეხილი" },
  { w: "სენა", popularity: 5, aliases: [], note: "მდინარე პარიზში" },
  { w: "სკანდინავიის მთები", popularity: 4, aliases: [], note: "მთათა სისტემა" },
  { w: "სამხრეთის ოკეანე", popularity: 4, aliases: ["ანტარქტიკის ოკეანე"], note: "ოკეანე" },
  { w: "სიცილია", popularity: 5, aliases: [], note: "უდიდესი კუნძული ხმელთაშუა ზღვაში" },
  { w: "სარდინია", popularity: 4, aliases: [], note: "კუნძული ხმელთაშუა ზღვაში" },

  // ტ
  { w: "ტაბაწყური", popularity: 5, aliases: ["ტაბაწყურის ტბა"], note: "მაღალმთიანი ტბა ჯავახეთში" },
  { w: "ტარიმის აუზი", popularity: 3, aliases: [], note: "გეოგრაფიული რეგიონი" },
  { w: "ტიბეტი", popularity: 5, aliases: [], note: "მსოფლიოს უდიდესი და უმაღლესი ზეგანი" },
  { w: "ტიტაკაკა", popularity: 5, aliases: ["ტიტიკაკა"], note: "მაღალმთიანი ტბა ანდებში" },
  { w: "ტანგანიიკა", popularity: 4, aliases: [], note: "ღრმა ტბა აფრიკაში" },
  { w: "ტაგო", popularity: 4, aliases: ["ტახო"], note: "იბერიის ნახევარკუნძულის უგრძესი მდინარე" },
  { w: "ტასმანია", popularity: 4, aliases: [], note: "კუნძული ავსტრალიასთან" },
  { w: "ტობავარჩხილი", popularity: 5, aliases: [], note: "ვერცხლის ტბა სამეგრელოს მთებში" },

  // უ
  { w: "უშბა", popularity: 5, aliases: [], note: "ლეგენდარული ორთავიანი მწვერვალი სვანეთში" },
  { w: "ურალი", popularity: 5, aliases: ["ურალის მთები", "მდინარე ურალი"], note: "საზღვარი ევროპასა და აზიას შორის" },
  { w: "უშგული", popularity: 5, aliases: [], note: "ევროპის ერთ-ერთი ყველაზე მაღალი დასახლებული პუნქტი" },
  { w: "უკაიალი", popularity: 3, aliases: [], note: "ამაზონის სათავე მდინარე" },
  { w: "უიუნის მლაშობი", popularity: 4, aliases: [], note: "მსოფლიოს უდიდესი მლაშობი ბოლივიაში" },
  { w: "ულურუ", popularity: 4, aliases: ["აიერს-როკი"], note: "წითელი მონოლითი ავსტრალიაში" },

  // ფ
  { w: "ფარავანი", popularity: 5, aliases: ["ფარავნის ტბა", "მდინარე ფარავანი"], note: "საქართველოს უდიდესი ტბა ფართობით" },
  { w: "ფუძიამა", popularity: 5, aliases: ["ფუჯი"], note: "იაპონიის წმინდა ვულკანი" },
  { w: "ფასისმთა", popularity: 4, aliases: [], note: "მწვერვალი კავკასიონზე" },
  { w: "ფილიპინის ზღვა", popularity: 4, aliases: [], note: "ზღვა წყნარ ოკეანეში" },
  { w: "ფიორდები", popularity: 5, aliases: ["ნორვეგიის ფიორდები"], note: "ზღვის ვიწრო ყურეები" },
  { w: "ფლორიდის სრუტე", popularity: 3, aliases: [], note: "სრუტე" },

  // ქ
  { w: "ქვაბლიანი", popularity: 4, aliases: [], note: "მდინარე სამცხეში" },
  { w: "ქვაცხელა", popularity: 3, aliases: [], note: "ხეობა" },
  { w: "ქილიმანჯარო", popularity: 5, aliases: ["კილიმანჯარო"], note: "ვულკანი აფრიკაში" },
  { w: "ქოლორადო", popularity: 4, aliases: ["კოლორადო"], note: "მდინარე" },
  { w: "ქსანი", popularity: 5, aliases: ["მდინარე ქსანი"], note: "მდინარე შიდა ქართლში" },

  // ღ
  { w: "ღალიძგა", popularity: 4, aliases: [], note: "მდინარე აფხაზეთში" },
  { w: "ღურდა", popularity: 3, aliases: [], note: "ხეობა" },
  { w: "ღობის ქედი", popularity: 2, aliases: [], note: "მთიანი ზოლი" },

  // ყ
  { w: "ყვირილა", popularity: 5, aliases: [], note: "მდინარე იმერეთში" },
  { w: "ყაზბეგი", popularity: 5, aliases: ["მყინვარწვერი"], note: "ცნობილი მთა კავკასიონზე" },
  { w: "ყარაკუმი", popularity: 5, aliases: [], note: "უდაბნო თურქმენეთში" },
  { w: "ყვითელი მდინარე", popularity: 5, aliases: ["ხუანხე"], note: "მდინარე ჩინეთში" },
  { w: "ყირიმის ნახევარკუნძული", popularity: 5, aliases: ["ყირიმი"], note: "ნახევარკუნძული შავ ზღვაში" },
  { w: "ყელის ტბა", popularity: 4, aliases: [], note: "მაღალმთიანი ტბა ვულკანურ ზეგანზე" },

  // შ
  { w: "შხარა", popularity: 5, aliases: [], note: "საქართველოს უმაღლესი მწვერვალი (5193 მ)" },
  { w: "შავი ზღვა", popularity: 5, aliases: [], note: "საქართველოს მოსაზღვრე ზღვა" },
  { w: "შაორის წყალსაცავი", popularity: 5, aliases: ["შაორი"], note: "წყალსაცავი რაჭაში" },
  { w: "შავიკლდე", popularity: 4, aliases: [], note: "მწვერვალი კახეთის კავკასიონზე" },
  { w: "შპიცბერგენი", popularity: 4, aliases: ["სვალბარდი"], note: "არქტიკული არქიპელაგი" },
  { w: "შოტლანდიის მთიანეთი", popularity: 4, aliases: [], note: "რეგიონი" },

  // ჩ
  { w: "ჩრდილოეთის ყინულოვანი ოკეანე", popularity: 5, aliases: [], note: "არქტიკული ოკეანე" },
  { w: "ჩანჩქერი ანხელი", popularity: 5, aliases: ["ანხელი"], note: "მსოფლიოს უმაღლესი ჩანჩქერი" },
  { w: "ჩრდილოეთის ზღვა", popularity: 5, aliases: [], note: "ზღვა ევროპაში" },
  { w: "ჩადის ტბა", popularity: 4, aliases: ["ჩადი"], note: "ტბა აფრიკაში" },
  { w: "ჩხოროწყუს მღვიმეები", popularity: 3, aliases: [], note: "გეოგრაფიული ობიექტი" },

  // ც
  { w: "ცხენისწყალი", popularity: 5, aliases: [], note: "დიდი მდინარე დასავლეთ საქართველოში" },
  { w: "ცხრაწყაროს უღელტეხილი", popularity: 4, aliases: ["ცხრაწყარო"], note: "უღელტეხილი თრიალეთის ქედზე" },
  { w: "ცენტრალური კავკასიონი", popularity: 4, aliases: [], note: "მთათა ზოლი" },
  { w: "ციმბირი", popularity: 5, aliases: [], note: "ჩრდილოეთ აზიის გიგანტური გეოგრაფიული რეგიონი" },
  { w: "ცეილონი", popularity: 4, aliases: ["შრი-ლანკა"], note: "კუნძული" },

  // ძ
  { w: "ძირულა", popularity: 5, aliases: [], note: "მდინარე იმერეთში" },
  { w: "ძამას ხეობა", popularity: 4, aliases: ["ძამა"], note: "მონასტრებით მდიდარი ხეობა შიდა ქართლში" },
  { w: "ძველი კოლხეთი", popularity: 3, aliases: [], note: "დაბლობი" },

  // წ
  { w: "წითელი ზღვა", popularity: 5, aliases: [], note: "ზღვა აფრიკასა და არაბეთის ნახევარკუნძულს შორის" },
  { w: "წალკის წყალსაცავი", popularity: 4, aliases: ["წალკა"], note: "წყალსაცავი ქვემო ქართლში" },
  { w: "წაღვერის ხეობა", popularity: 3, aliases: [], note: "ხეობა" },
  { w: "წებელდა", popularity: 3, aliases: [], note: "ხეობა აფხაზეთში" },

  // ჭ
  { w: "ჭოროხი", popularity: 5, aliases: [], note: "მდინარე სამხრეთ-დასავლეთ საქართველოში" },
  { w: "ჭაუხი", popularity: 5, aliases: ["ჭაუხის მთები", "კავკასიური დოლომიტები"], note: "მთის მასივი ხევში" },
  { w: "ჭანჭახი", popularity: 4, aliases: [], note: "მდინარე რაჭაში" },
  { w: "ჭალადიდის ჭაობი", popularity: 3, aliases: [], note: "დაბლობი" },

  // ხ
  { w: "ხობი", popularity: 5, aliases: ["ხობისწყალი"], note: "მდინარე სამეგრელოში" },
  { w: "ხრამი", popularity: 5, aliases: [], note: "მდინარე აღმოსავლეთ საქართველოში" },
  { w: "ხევისბერი", popularity: 3, aliases: [], note: "ხეობა" },
  { w: "ხმელთაშუა ზღვა", popularity: 5, aliases: [], note: "ზღვა ევროპას, აზიასა და აფრიკას შორის" },
  { w: "ხუანხე", popularity: 5, aliases: ["ყვითელი მდინარე"], note: "დიდი მდინარე ჩინეთში" },
  { w: "ხადის ხეობა", popularity: 4, aliases: ["ხადა"], note: "ხეობა მთიულეთში" },
  { w: "ხორასანი", popularity: 3, aliases: [], note: "ისტორიული რეგიონი" },

  // ჯ
  { w: "ჯანღა", popularity: 5, aliases: ["ჯანღითაუ"], note: "მწვერვალი კავკასიონზე (5059 მ)" },
  { w: "ჯავახეთის ზეგანი", popularity: 5, aliases: ["ჯავახეთი"], note: "ვულკანური ზეგანი სამხრეთ საქართველოში" },
  { w: "ჯომოლუნგმა", popularity: 5, aliases: ["ევერესტი"], note: "მსოფლიოს უმაღლესი მთა" },
  { w: "ჯვრის უღელტეხილი", popularity: 5, aliases: [], note: "უღელტეხილი საქართველოს სამხედრო გზაზე" },
  { w: "ჯიხა", popularity: 3, aliases: [], note: "მთა" },
  { w: "ჯიბრალტარი", popularity: 4, aliases: ["გიბრალტარი"], note: "სრუტე" },

  // ჰ
  { w: "ჰიმალაი", popularity: 5, aliases: ["ჰიმალაის მთები"], note: "მსოფლიოს უმაღლესი მთათა სისტემა" },
  { w: "ჰუდზონის ყურე", popularity: 5, aliases: ["ჰუდსონი"], note: "უზარმაზარი ყურე კანადაში" },
  { w: "ჰავაის კუნძულები", popularity: 5, aliases: ["ჰავაი"], note: "ვულკანური არქიპელაგი წყნარ ოკეანეში" },
  { w: "ჰუანხე", popularity: 4, aliases: ["ხუანხე"], note: "მდინარე ჩინეთში" },
  { w: "ჰეკლა", popularity: 4, aliases: [], note: "ცნობილი ვულკანი ისლანდიაში" },
  { w: "ჰურონის ტბა", popularity: 4, aliases: ["ჰურონი"], note: "ჩრდილოეთ ამერიკის დიდი ტბა" },
  { w: "ჰორნის კონცხი", popularity: 4, aliases: [], note: "კონცხი სამხრეთ ამერიკის კიდეზე" },
  { w: "ჰადსონის სრუტე", popularity: 3, aliases: [], note: "სრუტე კანადაში" },
  { w: "ჰავაის არქიპელაგი", popularity: 4, aliases: [], note: "კუნძულები წყნარ ოკეანეში" },

  // Additional Georgian & Global features
  { w: "აჭარისწყალი", popularity: 5, aliases: [], note: "მდინარე აჭარაში" },
  { w: "აბანოს უღელტეხილი", popularity: 4, aliases: [], note: "თუშეთის უღელტეხილი" },
  { w: "არაგვის ხეობა", popularity: 5, aliases: [], note: "ხეობა აღმოსავლეთ საქართველოში" },
  { w: "ანტარქტიდა", popularity: 5, aliases: [], note: "ყინულოვანი კონტინენტი" },
  { w: "აპენინები", popularity: 4, aliases: [], note: "მთები იტალიაში" },
  { w: "ატაკამის უდაბნო", popularity: 4, aliases: [], note: "მსოფლიოს ყველაზე მშრალი უდაბნო ჩილეში" },
  { w: "ალაზნის ველი", popularity: 5, aliases: [], note: "ნაყოფიერი ბარი კახეთში" },
  { w: "ბორჯომის ხეობა", popularity: 5, aliases: [], note: "ხეობა მტკვარზე" },
  { w: "ბზიფის ქედი", popularity: 4, aliases: [], note: "ქედი აფხაზეთში" },
  { w: "ბალკანეთის ნახევარკუნძული", popularity: 4, aliases: ["ბალკანეთი"], note: "ნახევარკუნძული ევროპაში" },
  { w: "გომბორის ქედი", popularity: 5, aliases: ["ცივ-გომბორი"], note: "ქედი კახეთში" },
  { w: "გარეჯის უდაბნო", popularity: 5, aliases: ["დავით-გარეჯი"], note: "ნახევარუდაბნო კახეთში" },
  { w: "გუდამაყრის ხეობა", popularity: 4, aliases: [], note: "ხეობა მთიულეთში" },
  { w: "დოლომიტები", popularity: 4, aliases: [], note: "მთები იტალიის ალპებში" },
  { w: "დრავა", popularity: 3, aliases: [], note: "მდინარე ევროპაში" },
  { w: "ენგურის წყალსაცავი", popularity: 5, aliases: [], note: "უდიდესი თაღოვანი კაშხალი" },
  { w: "თრიალეთის ქედი", popularity: 5, aliases: [], note: "ქედი შიდა ქართლსა და სამცხეში" },
  { w: "თეთრი არაგვი", popularity: 4, aliases: [], note: "არაგვის სათავე" },
  { w: "ივრის ზეგანი", popularity: 4, aliases: [], note: "ზეგანი კახეთში" },
  { w: "იონეთის ზღვა", popularity: 4, aliases: [], note: "ზღვა საბერძნეთთან" },
  { w: "იორდანე", popularity: 5, aliases: ["მდინარე იორდანე"], note: "წმინდა მდინარე ახლო აღმოსავლეთში" },
  { w: "კოლხეთის დაბლობი", popularity: 5, aliases: [], note: "დაბლობი დასავლეთ საქართველოში" },
  { w: "კოდორის ხეობა", popularity: 5, aliases: [], note: "ხეობა აფხაზეთში" },
  { w: "კრეტა", popularity: 5, aliases: [], note: "საბერძნეთის უდიდესი კუნძული" },
  { w: "კორსიკა", popularity: 4, aliases: [], note: "კუნძული ხმელთაშუა ზღვაში" },
  { w: "ლიხის ქედი", popularity: 5, aliases: ["სურამის ქედი"], note: "წყალგამყოფი ქედი" },
  { w: "მესხეთის ქედი", popularity: 4, aliases: [], note: "ქედი სამხრეთ საქართველოში" },
  { w: "მუხრანის ველი", popularity: 4, aliases: [], note: "ბარი შიდა ქართლში" },
  { w: "მარმარილოს ზღვა", popularity: 4, aliases: [], note: "ზღვა თურქეთში" },
  { w: "ნევა", popularity: 4, aliases: [], note: "მდინარე სანქტ-პეტერბურგში" },
  { w: "პატაგონია", popularity: 4, aliases: [], note: "გეოგრაფიული მხარე სამხრეთ ამერიკაში" },
  { w: "რაჭის ქედი", popularity: 4, aliases: [], note: "ქედი დასავლეთ საქართველოში" },
  { w: "რიონის ხეობა", popularity: 5, aliases: [], note: "ხეობა იმერეთსა და რაჭაში" },
  { w: "სვანეთის ქედი", popularity: 5, aliases: [], note: "ქედი კავკასიონზე" },
  { w: "ფშავის არაგვი", popularity: 4, aliases: [], note: "არაგვის შენაკადი" },
  { w: "ქართლის ვაკე", popularity: 5, aliases: [], note: "ვაკე აღმოსავლეთ საქართველოში" },
  { w: "ქსნის ხეობა", popularity: 4, aliases: [], note: "ხეობა შიდა ქართლში" },
  { w: "შავი არაგვი", popularity: 4, aliases: [], note: "მდინარე მთიულეთში" },
  { w: "შავშეთის ქედი", popularity: 4, aliases: [], note: "ქედი სამხრეთ საქართველოში" },
  { w: "ჩხერიმელა", popularity: 4, aliases: [], note: "მდინარე იმერეთში" },
  { w: "ცხენისწყლის ხეობა", popularity: 4, aliases: [], note: "ხეობა ლეჩხუმში" },
  { w: "წიფის უღელტეხილი", popularity: 3, aliases: [], note: "უღელტეხილი ლიხის ქედზე" },
  { w: "ხრამის კანიონი", popularity: 4, aliases: [], note: "კანიონი ქვემო ქართლში" },
  { w: "ჯავახეთის ქედი", popularity: 4, aliases: [], note: "ვულკანური ქედი" }
];
