// tools/builders/plants.js
module.exports = [
  // ა
  { w: "აკაცია", popularity: 5, aliases: [], note: "ხე" },
  { w: "ატამი", popularity: 5, aliases: [], note: "ხეხილი" },
  { w: "ალუჩა", popularity: 5, aliases: [], note: "ხეხილი" },
  { w: "ალუბალი", popularity: 5, aliases: [], note: "ხეხილი" },
  { w: "ანანასი", popularity: 5, aliases: [], note: "ტროპიკული ხილი" },
  { w: "ავოკადო", popularity: 5, aliases: [], note: "ტროპიკული ხილი" },
  { w: "ასკილი", popularity: 5, aliases: [], note: "სამკურნალო ბუჩქი" },
  { w: "არყი", popularity: 4, aliases: [], note: "ხე" },
  { w: "ანისული", popularity: 4, aliases: [], note: "სანელებელი მცენარე" },
  { w: "ალოე", popularity: 5, aliases: [], note: "სამკურნალო სუკულენტი" },
  { w: "აბზინდა", popularity: 4, aliases: [], note: "მწარე სამკურნალო ბალახი" },
  { w: "არტიშოკი", popularity: 4, aliases: [], note: "ბოსტნეული" },
  { w: "ასპარაგუსი", popularity: 4, aliases: ["სატაცური"], note: "დელიკატესური მცენარე" },
  { w: "არაქისი", popularity: 5, aliases: ["მიწის თხილი"], note: "პარკოსანი მცენარე" },
  { w: "აგავა", popularity: 4, aliases: [], note: "სუკულენტი" },
  { w: "ამარილისი", popularity: 3, aliases: [], note: "დეკორატიული ყვავილი" },
  { w: "აზალია", popularity: 4, aliases: [], note: "დეკორატიული ყვავილი" },
  { w: "ალვის ხე", popularity: 5, aliases: ["ტოპოლი"], note: "მაღალი ხე" },
  { w: "არდიში", popularity: 3, aliases: [], note: "ბუჩქი" },
  { w: "აცეტოზა", popularity: 2, aliases: ["მჟაუნა"], note: "მჟავე ბალახი" },

  // ბ
  { w: "ბანანი", popularity: 5, aliases: [], note: "ტროპიკული მცენარე და ნაყოფი" },
  { w: "ბალი", popularity: 5, aliases: [], note: "ხეხილი" },
  { w: "ბროწეული", popularity: 5, aliases: [], note: "ხეხილი" },
  { w: "ბადრიჯანი", popularity: 5, aliases: [], note: "ბოსტნეული" },
  { w: "ბოლოკი", popularity: 5, aliases: [], note: "ძირხვენა ბოსტნეული" },
  { w: "ბარდა", popularity: 5, aliases: [], note: "პარკოსანი" },
  { w: "ბალბა", popularity: 4, aliases: [], note: "სამკურნალო მცენარე" },
  { w: "ბზა", popularity: 5, aliases: [], note: "მარადმწვანე ბუჩქი" },
  { w: "ბამბუკი", popularity: 5, aliases: [], note: "მარცვლოვანი გიგანტური მცენარე" },
  { w: "ბეგონია", popularity: 4, aliases: [], note: "ოთახის ყვავილი" },
  { w: "ბეგქონდარა", popularity: 5, aliases: ["ქონდარი"], note: "სურნელოვანი სანელებელი" },
  { w: "ბაბუაწვერა", popularity: 5, aliases: [], note: "ყვითელი მინდვრის ყვავილი" },
  { w: "ბრინჯი", popularity: 5, aliases: [], note: "მარცვლეული კულტურა" },
  { w: "ბარბარისი", popularity: 4, aliases: ["კოწახური"], note: "კენკროვანი ბუჩქი" },
  { w: "ბაობაბი", popularity: 4, aliases: [], note: "აფრიკული გიგანტური ხე" },
  { w: "ბამბა", popularity: 5, aliases: [], note: "ბოჭკოვანი კულტურა" },
  { w: "ბარამბო", popularity: 4, aliases: ["მელისა"], note: "სამკურნალო ბალახი" },
  { w: "ბაბუა-წვერა", popularity: 4, aliases: ["ბაბუაწვერა"], note: "ყვავილი" },
  { w: "ბროკოლი", popularity: 5, aliases: [], note: "კომბოსტოსებრთა ოჯახის ბოსტნეული" },
  { w: "ბექობის ბალახი", popularity: 3, aliases: [], note: "მინდვრის მცენარე" },

  // გ
  { w: "გვირილა", popularity: 5, aliases: [], note: "მინდვრის თეთრყვავილა მცენარე" },
  { w: "გოგრა", popularity: 5, aliases: [], note: "ბაღჩეული კულტურა" },
  { w: "გლადიოლუსი", popularity: 4, aliases: [], note: "ბოლქვიანი დეკორატიული ყვავილი" },
  { w: "გვიმრა", popularity: 5, aliases: [], note: "სპოროვანი მცენარე" },
  { w: "გერანიუმი", popularity: 4, aliases: ["ნემსიწვერა"], note: "ოთახის ყვავილი" },
  { w: "გრეიპფრუტი", popularity: 5, aliases: [], note: "ციტრუსი" },
  { w: "გინგკო", popularity: 4, aliases: [], note: "უძველესი ხე" },
  { w: "გულყვითელა", popularity: 4, aliases: ["კალენდულა"], note: "სამკურნალო ყვავილი" },
  { w: "გლიცინია", popularity: 3, aliases: [], note: "მცოცავი მცენარე" },
  { w: "გაზანია", popularity: 3, aliases: [], note: "ყვავილი" },
  { w: "გველისმხოკავი", popularity: 3, aliases: [], note: "ბალახი" },
  { w: "გაცხა", popularity: 3, aliases: [], note: "ხე" },
  { w: "გრავიოლა", popularity: 3, aliases: [], note: "ეგზოტიკური მცენარე" },
  { w: "გარეული ვაზი", popularity: 4, aliases: ["კრიკინა"], note: "ტყის მცენარე" },
  { w: "გუავა", popularity: 4, aliases: [], note: "ტროპიკული ხილი" },

  // დ
  { w: "დაფნა", popularity: 5, aliases: [], note: "სურნელოვანი მარადმწვანე ხე" },
  { w: "დეკა", popularity: 4, aliases: [], note: "კავკასიური როდოდენდრონი" },
  { w: "დუმფარა", popularity: 4, aliases: [], note: "წყლის მცენარე" },
  { w: "დენდრობიუმი", popularity: 3, aliases: [], note: "ორქიდეა" },
  { w: "დროზერა", popularity: 3, aliases: ["მწერიჭამია მცენარე"], note: "ხორცისმჭამელი მცენარე" },
  { w: "დვალურა", popularity: 3, aliases: [], note: "ტყის ბალახი" },
  { w: "დიოსკორეა", popularity: 3, aliases: [], note: "სამკურნალო ლიანა" },
  { w: "დედოფლის ყვავილი", popularity: 4, aliases: [], note: "ყვავილი" },
  { w: "დინდგელი", popularity: 3, aliases: [], note: "ფისოვანი მცენარეული პროდუქტი" },
  { w: "დრაცენა", popularity: 4, aliases: [], note: "ოთახის მცენარე" },
  { w: "დურიანი", popularity: 4, aliases: [], note: "სპეციფიკური სუნის ტროპიკული ხილი" },

  // ე
  { w: "ევკალიპტი", popularity: 5, aliases: [], note: "ავსტრალიური მარადმწვანე ხე" },
  { w: "ედელვაისი", popularity: 4, aliases: [], note: "ალპური იშვიათი ყვავილი" },
  { w: "ექინაცეა", popularity: 4, aliases: [], note: "იმუნიტეტის გამაძლიერებელი ყვავილი" },
  { w: "ენდრო", popularity: 5, aliases: [], note: "წითელი საღებავი მცენარე" },
  { w: "ენძელა", popularity: 5, aliases: [], note: "გაზაფხულის პირველი ყვავილი" },
  { w: "ერიკა", popularity: 3, aliases: [], note: "ბუჩქბალახი" },
  { w: "ესპარცეტი", popularity: 3, aliases: [], note: "საკვები ბალახი" },
  { w: "ელოდეა", popularity: 3, aliases: [], note: "წყლის მცენარე" },
  { w: "ეფედრა", popularity: 3, aliases: [], note: "სამკურნალო მცენარე" },
  { w: "ეტრუგა", popularity: 2, aliases: [], note: "ციტრუსი" },

  // ვ
  { w: "ვარდი", popularity: 5, aliases: [], note: "ყვავილების დედოფალი" },
  { w: "ვაშლი", popularity: 5, aliases: [], note: "პოპულარული ხეხილი" },
  { w: "ვაზი", popularity: 5, aliases: ["ყურძნის ვაზი"], note: "ქართული კულტურული მცენარე" },
  { w: "ვერხვი", popularity: 5, aliases: [], note: "ფოთლოვანი ხე" },
  { w: "ვანილი", popularity: 5, aliases: [], note: "სურნელოვანი ორქიდეა" },
  { w: "ვალერიანი", popularity: 5, aliases: ["კატაბალახა"], note: "დამამშვიდებელი სამკურნალო მცენარე" },
  { w: "ვარდკაჭკაჭა", popularity: 4, aliases: ["ციკორი"], note: "ყავის შემცვლელი ბალახი" },
  { w: "ვაშლატამა", popularity: 5, aliases: ["ნექტარინი"], note: "ხეხილი" },
  { w: "ვიოლა", popularity: 4, aliases: ["იაჟუჟუნა"], note: "ყვავილი" },
  { w: "ვერბენა", popularity: 3, aliases: [], note: "სამკურნალო ყვავილი" },
  { w: "ვიისტერია", popularity: 3, aliases: ["გლიცინია"], note: "ყვავილოვანი ლიანა" },
  { w: "ვასილაკი", popularity: 3, aliases: ["ღიღილო"], note: "მინდვრის ყვავილი" },

  // ზ
  { w: "ზამბახი", popularity: 5, aliases: ["ირისი"], note: "დეკორატიული ყვავილი" },
  { w: "ზეთისხილი", popularity: 5, aliases: ["ოლივა"], note: "ხმელთაშუაზღვისპირა კულტურა" },
  { w: "ზაფრანა", popularity: 5, aliases: ["შაფრანი"], note: "ძვირფასი სანელებელი" },
  { w: "ზღმარტლი", popularity: 4, aliases: [], note: "ტყის ხილი" },
  { w: "ზიზილა", popularity: 4, aliases: [], note: "მინდვრის პატარა ყვავილი" },
  { w: "ზაზუნა-ბალახი", popularity: 3, aliases: [], note: "ბალახოვანი მცენარე" },
  { w: "ზღვის კომბოსტო", popularity: 4, aliases: ["ლამინარია"], note: "წყალმცენარე" },
  { w: "ზურმუხტა", popularity: 3, aliases: [], note: "მცენარე" },

  // თ
  { w: "თხილი", popularity: 5, aliases: [], note: "კაკლოვანი ბუჩქი" },
  { w: "თუთა", popularity: 5, aliases: ["შელამურა"], note: "აბრეშუმის ჭიის საკვები ხე" },
  { w: "თელა", popularity: 5, aliases: [], note: "ფოთლოვანი ხე" },
  { w: "თამბაქო", popularity: 5, aliases: [], note: "ტექნიკური კულტურა" },
  { w: "თალგამი", popularity: 4, aliases: [], note: "ძირხვენა ბოსტნეული" },
  { w: "თავშავა", popularity: 4, aliases: ["ორეგანო"], note: "სურნელოვანი სანელებელი" },
  { w: "თრიმლი", popularity: 4, aliases: [], note: "მთრიმლავი ბუჩქი" },
  { w: "თეთრი სამყურა", popularity: 4, aliases: [], note: "საფურაჟე ბალახი" },
  { w: "თაგვანა", popularity: 3, aliases: [], note: "ტყის მცენარე" },
  { w: "თაფლაკა", popularity: 3, aliases: [], note: "თაფლოვანი მცენარე" },
  { w: "თეთრყვავილა", popularity: 4, aliases: [], note: "გაზაფხულის ყვავილი" },
  { w: "თივაქასრა", popularity: 3, aliases: [], note: "მარცვლოვანი ბალახი" },

  // ი
  { w: "ია", popularity: 5, aliases: [], note: "გაზაფხულის ნაზი ყვავილი" },
  { w: "იასამანი", popularity: 5, aliases: [], note: "სურნელოვანი გაზაფხულის ბუჩქი" },
  { w: "იფანი", popularity: 5, aliases: [], note: "ტყის ძვირფასი ხე" },
  { w: "იელი", popularity: 4, aliases: ["ყვითელი როდოდენდრონი"], note: "შხამიანი ულამაზესი ბუჩქი" },
  { w: "იონჯა", popularity: 5, aliases: [], note: "საუკეთესო საკვები ბალახი" },
  { w: "ირისი", popularity: 4, aliases: ["ზამბახი"], note: "ყვავილი" },
  { w: "იუკა", popularity: 4, aliases: [], note: "მარადმწვანე მცენარე" },
  { w: "ივან-ჩაი", popularity: 4, aliases: ["კვიპრი"], note: "ჩაისებრი მცენარე" },
  { w: "იაჟუჟუნა", popularity: 4, aliases: ["ვიოლა"], note: "ფერადი ყვავილი" },
  { w: "იერუსალიმის არტიშოკი", popularity: 3, aliases: ["ტოპინამბური"], note: "ძირხვენა" },

  // კ
  { w: "კაკალი", popularity: 5, aliases: [], note: "კაკლოვანი ხე" },
  { w: "კაქტუსი", popularity: 5, aliases: [], note: "უდაბნოს სუკულენტი" },
  { w: "კომბოსტო", popularity: 5, aliases: [], note: "ბოსტნეული" },
  { w: "კიტრი", popularity: 5, aliases: [], note: "ბოსტნეული" },
  { w: "კარტოფილი", popularity: 5, aliases: [], note: "ძირითადი ბოსტნეული" },
  { w: "კედარი", popularity: 5, aliases: [], note: "წიწვოვანი გიგანტი" },
  { w: "კვიპაროსი", popularity: 5, aliases: [], note: "მარადმწვანე ხე" },
  { w: "კოწახური", popularity: 4, aliases: [], note: "კენკრა" },
  { w: "კამა", popularity: 5, aliases: [], note: "მწვანილი" },
  { w: "კოჭა", popularity: 5, aliases: ["ჯანჯაფილი", "იმბირი"], note: "სამკურნალო ფესვი" },
  { w: "კამელია", popularity: 4, aliases: [], note: "დეკორატიული ყვავილოვანი ბუჩქი" },
  { w: "კესანე", popularity: 4, aliases: [], note: "ცისფერი პატარა ყვავილი" },
  { w: "კუნელი", popularity: 4, aliases: [], note: "სამკურნალო კენკროვანი ხე" },
  { w: "კაკაო", popularity: 5, aliases: [], note: "შოკოლადის ხე" },
  { w: "კივი", popularity: 5, aliases: [], note: "ტროპიკული ხილი" },
  { w: "კომში", popularity: 5, aliases: ["ბია"], note: "ხეხილი" },
  { w: "კოლხური ბზა", popularity: 4, aliases: [], note: "რელიქტური მცენარე" },
  { w: "კალენდულა", popularity: 4, aliases: ["გულყვითელა"], note: "ყვავილი" },
  { w: "კარალიოკი", popularity: 4, aliases: ["ხურმა"], note: "ხეხილი" },

  // ლ
  { w: "ლეღვი", popularity: 5, aliases: [], note: "სუბტროპიკული ხეხილი" },
  { w: "ლიმონი", popularity: 5, aliases: [], note: "ციტრუსი" },
  { w: "ლავანდა", popularity: 5, aliases: [], note: "სურნელოვანი იასამნისფერი ყვავილი" },
  { w: "ლოტოსი", popularity: 5, aliases: [], note: "წმინდა წყლის ყვავილი" },
  { w: "ლიანა", popularity: 5, aliases: [], note: "მცოცავი მცენარე" },
  { w: "ლობიო", popularity: 5, aliases: [], note: "პარკოსანი ბოსტნეული" },
  { w: "ლარიქსი", popularity: 4, aliases: ["ფოთოლმცვენი წიწვი"], note: "ხე" },
  { w: "ლაფანი", popularity: 4, aliases: [], note: "ხე" },
  { w: "ლერწამი", popularity: 5, aliases: [], note: "ჭაობის მცენარე" },
  { w: "ლუპინი", popularity: 3, aliases: [], note: "ყვავილოვანი მცენარე" },
  { w: "ლაიმი", popularity: 5, aliases: [], note: "მწვანე ციტრუსი" },
  { w: "ლიჩი", popularity: 4, aliases: [], note: "ეგზოტიკური ხილი" },

  // მ
  { w: "მუხა", popularity: 5, aliases: [], note: "ტყის მძლავრი ხე" },
  { w: "მზესუმზირა", popularity: 5, aliases: [], note: "ზეთოვანი ყვავილი" },
  { w: "მანგო", popularity: 5, aliases: [], note: "ტროპიკული ხილი" },
  { w: "მანდარინი", popularity: 5, aliases: [], note: "ციტრუსი" },
  { w: "მარწყვი", popularity: 5, aliases: [], note: "კენკროვანი ხილი" },
  { w: "მაყვალი", popularity: 5, aliases: [], note: "ეკლიანი ბუჩქი და კენკრა" },
  { w: "მოცვი", popularity: 5, aliases: [], note: "ტყის სასარგებლო კენკრა" },
  { w: "მიხაკი", popularity: 5, aliases: [], note: "ყვავილი და სანელებელი" },
  { w: "მურყანი", popularity: 4, aliases: ["თხმელა"], note: "ტყის ხე" },
  { w: "მუხუდო", popularity: 4, aliases: [], note: "პარკოსანი" },
  { w: "მრავალძარღვა", popularity: 5, aliases: [], note: "სამკურნალო ბალახი" },
  { w: "მსხალი", popularity: 5, aliases: [], note: "ხეხილი" },
  { w: "მაგნოლია", popularity: 5, aliases: [], note: "დიდყვავილა მარადმწვანე ხე" },
  { w: "მელისა", popularity: 4, aliases: ["ბარამბო"], note: "სამკურნალო ბალახი" },
  { w: "მჟაუნა", popularity: 4, aliases: [], note: "მწვანილი" },
  { w: "მაჩიტა", popularity: 3, aliases: [], note: "მინდვრის ყვავილი" },

  // ნ
  { w: "ნუში", popularity: 5, aliases: [], note: "კაკლოვანი ხეხილი" },
  { w: "ნესვი", popularity: 5, aliases: [], note: "ბაღჩეული კულტურა" },
  { w: "ნარგიზი", popularity: 5, aliases: ["ნარცისი"], note: "საგაზაფხულო ყვავილი" },
  { w: "ნაძვი", popularity: 5, aliases: [], note: "საახალწლო წიწვოვანი ხე" },
  { w: "ნიორი", popularity: 5, aliases: [], note: "ბოსტნეული და სანელებელი" },
  { w: "ნიახური", popularity: 5, aliases: [], note: "მწვანილი და ბოსტნეული" },
  { w: "ნარშავი", popularity: 4, aliases: [], note: "ეკლიანი მცენარე" },
  { w: "ნარინჯი", popularity: 4, aliases: [], note: "მწარე ფორთოხალი" },
  { w: "ნექტარინი", popularity: 5, aliases: ["ვაშლატამა"], note: "ხეხილი" },
  { w: "ნემსიწვერა", popularity: 4, aliases: ["გერანი"], note: "ყვავილი" },
  { w: "ნაღველა", popularity: 3, aliases: [], note: "სამკურნალო მცენარე" },
  { w: "ნუკრი", popularity: 3, aliases: [], note: "მცენარე" },

  // ო
  { w: "ორქიდეა", popularity: 5, aliases: [], note: "ეგზოტიკური ყვავილი" },
  { w: "ოლეანდრი", popularity: 4, aliases: [], note: "მარადმწვანე დეკორატიული ბუჩქი" },
  { w: "ოხრახუში", popularity: 5, aliases: [], note: "პოპულარული მწვანილი" },
  { w: "ოთხფოთოლა სამყურა", popularity: 4, aliases: [], note: "იღბლის სიმბოლო" },
  { w: "ოქროწკეპლა", popularity: 3, aliases: [], note: "სამკურნალო ყვავილი" },
  { w: "ოლღა", popularity: 3, aliases: [], note: "მცენარე" },
  { w: "ორკბილა", popularity: 3, aliases: [], note: "სამკურნალო ბალახი" },
  { w: "ოფი", popularity: 2, aliases: [], note: "ხე" },

  // პ
  { w: "პალმა", popularity: 5, aliases: [], note: "სამხრეთის ხე" },
  { w: "პომიდორი", popularity: 5, aliases: ["ტომატი"], note: "ბოსტნეული" },
  { w: "პიტნა", popularity: 5, aliases: [], note: "სურნელოვანი მწვანილი" },
  { w: "პეტუნია", popularity: 4, aliases: [], note: "დეკორატიული ყვავილი" },
  { w: "პაპაია", popularity: 4, aliases: [], note: "ტროპიკული ხილი" },
  { w: "პაპირუსი", popularity: 4, aliases: [], note: "ძველეგვიპტური ჭაობის მცენარე" },
  { w: "პეონი", popularity: 4, aliases: ["იორდასალამი"], note: "დიდი ყვავილი" },
  { w: "პილპილი", popularity: 5, aliases: [], note: "ცხარე სანელებელი" },
  { w: "პრასი", popularity: 4, aliases: [], note: "ბოსტნეული" },
  { w: "პასიფლორა", popularity: 3, aliases: ["ვნების ყვავილი"], note: "ლიანა" },
  { w: "პატისონი", popularity: 3, aliases: [], note: "გოგრისებრი ბოსტნეული" },

  // ჟ
  { w: "ჟოლო", popularity: 5, aliases: ["მალინა"], note: "ტკბილი წითელი კენკრა" },
  { w: "ჟასმინი", popularity: 5, aliases: [], note: "სურნელოვანი ყვავილოვანი ბუჩქი" },
  { w: "ჟენშენი", popularity: 5, aliases: [], note: "სიცოცხლის ფესვი" },
  { w: "ჟოლოსფერი სამყურა", popularity: 3, aliases: [], note: "საკვები ბალახი" },
  { w: "ჟანგა", popularity: 3, aliases: [], note: "პარაზიტი სოკო მცენარეებზე" },
  { w: "ჟონჟოლი", popularity: 4, aliases: ["ჯონჯოლი"], note: "მწნილის მცენარე" },

  // რ
  { w: "როზმარინი", popularity: 5, aliases: [], note: "ხმელთაშუაზღვისპირა სანელებელი" },
  { w: "რევანდი", popularity: 4, aliases: [], note: "მჟავე ღეროიანი მცენარე" },
  { w: "რაფსია", popularity: 4, aliases: ["რაფსი"], note: "ზეთოვანი მცენარე" },
  { w: "რცხილა", popularity: 5, aliases: [], note: "ტყის მაგარი ხე" },
  { w: "რუკოლა", popularity: 5, aliases: [], note: "სალათის ფოთოლი" },
  { w: "როდოდენდრონი", popularity: 4, aliases: ["დეკა"], note: "მთის ყვავილოვანი ბუჩქი" },
  { w: "რუთა", popularity: 3, aliases: [], note: "სამკურნალო ბალახი" },
  { w: "რაფლეზია", popularity: 4, aliases: [], note: "მსოფლიოში უდიდესი ყვავილი" },
  { w: "რაფია", popularity: 3, aliases: [], note: "პალმის სახეობა" },

  // ს
  { w: "სოსანი", popularity: 4, aliases: ["შროშანა"], note: "ყვავილი" },
  { w: "სოჭი", popularity: 5, aliases: [], note: "წიწვოვანი ტყის ხე" },
  { w: "სამყურა", popularity: 5, aliases: [], note: "მინდვრის ბალახი" },
  { w: "სელი", popularity: 5, aliases: [], note: "სართავი და ზეთოვანი მცენარე" },
  { w: "სოია", popularity: 5, aliases: [], note: "ცილოვანი პარკოსანი" },
  { w: "სვია", popularity: 4, aliases: [], note: "ლუდის წარმოების მცენარე" },
  { w: "სიმინდი", popularity: 5, aliases: [], note: "მარცვლეული" },
  { w: "სატაცური", popularity: 5, aliases: ["ასპარაგუსი"], note: "გაზაფხულის დელიკატესი" },
  { w: "სალბი", popularity: 5, aliases: ["შალფეი"], note: "სამკურნალო მცენარე" },
  { w: "სანდალოზის ხე", popularity: 4, aliases: [], note: "სურნელოვანი ხე" },
  { w: "სეკვოია", popularity: 5, aliases: [], note: "მსოფლიოს უმაღლესი ხე" },
  { w: "სურო", popularity: 5, aliases: [], note: "მარადმწვანე მხვიარა მცენარე" },
  { w: "სტაფილო", popularity: 5, aliases: [], note: "ნარინჯისფერი ძირხვენა" },
  { w: "სოკო", popularity: 5, aliases: [], note: "ტყის საჩუქარი" },

  // ტ
  { w: "ტიტა", popularity: 5, aliases: [], note: "საგაზაფხულო ბოლქვიანი ყვავილი" },
  { w: "ტირიფი", popularity: 5, aliases: ["მტირალა ტირიფი"], note: "წყლისპირა ხე" },
  { w: "ტარხუნა", popularity: 5, aliases: [], note: "სურნელოვანი მწვანილი" },
  { w: "ტუია", popularity: 4, aliases: [], note: "მარადმწვანე წიწვოვანი დეკორატიული ხე" },
  { w: "ტყემალი", popularity: 5, aliases: [], note: "ქართული საწებლის ხეხილი" },
  { w: "ტუბეროზა", popularity: 3, aliases: [], note: "სურნელოვანი ყვავილი" },
  { w: "ტურნეფსი", popularity: 3, aliases: [], note: "საკვები ძირხვენა" },
  { w: "ტორფი", popularity: 3, aliases: [], note: "მცენარეული ნამარხი" },

  // უ
  { w: "ურთხელი", popularity: 4, aliases: ["უთხოვარი"], note: "მარადმწვანე რელიქტური წიწვოვანი" },
  { w: "უკვდავა", popularity: 4, aliases: ["უკვდავება"], note: "სამკურნალო მინდვრის ყვავილი" },
  { w: "უნაბი", popularity: 4, aliases: ["ჩინური ფინიკი"], note: "სამკურნალო ხეხილი" },
  { w: "უთხოვარი", popularity: 4, aliases: ["ურთხელი"], note: "წითელი ხე" },
  { w: "უსურვაზი", popularity: 3, aliases: [], note: "ტყის ველური ვაზი" },
  { w: "უზანი", popularity: 3, aliases: [], note: "ბუჩქი" },

  // ფ
  { w: "ფიჭვი", popularity: 5, aliases: [], note: "წიწვოვანი ხე" },
  { w: "ფიკუსი", popularity: 5, aliases: [], note: "პოპულარული ოთახის მცენარე" },
  { w: "ფუქსია", popularity: 4, aliases: [], note: "დეკორატიული ყვავილი" },
  { w: "ფურისულა", popularity: 4, aliases: ["პრიმულა"], note: "საგაზაფხულო ყვავილი" },
  { w: "ფისტა", popularity: 5, aliases: ["ფსტა"], note: "კაკლოვანი ხე" },
  { w: "ფეტვი", popularity: 4, aliases: [], note: "მარცვლეული" },
  { w: "ფინიკის პალმა", popularity: 5, aliases: ["ფინიკი"], note: "ტროპიკული ხე" },
  { w: "ფორთოხალი", popularity: 5, aliases: [], note: "ციტრუსი" },
  { w: "ფეიხოა", popularity: 5, aliases: [], note: "სუბტროპიკული ხილი" },
  { w: "ფითრი", popularity: 4, aliases: [], note: "მარადმწვანე ბუჩქი" },
  { w: "ფილოდენდრონი", popularity: 3, aliases: [], note: "ოთახის მცენარე" },

  // ქ
  { w: "ქლიავი", popularity: 5, aliases: [], note: "ხეხილი" },
  { w: "ქინძი", popularity: 5, aliases: ["კორიანდრი"], note: "ტრადიციული ქართული მწვანილი" },
  { w: "ქერი", popularity: 5, aliases: [], note: "ძირითადი მარცვლეული" },
  { w: "ქრიზანთემა", popularity: 5, aliases: [], note: "შემოდგომის ყვავილი" },
  { w: "ქაცვი", popularity: 4, aliases: [], note: "ვიტამინებით მდიდარი ნარინჯისფერი კენკრა" },
  { w: "ქაფურის ხე", popularity: 4, aliases: [], note: "მარადმწვანე ხე" },
  { w: "ქამა სოკო", popularity: 5, aliases: ["ქამა"], note: "საჭმელი სოკო" },
  { w: "ქონდარი", popularity: 5, aliases: ["ბეგქონდარა"], note: "სანელებელი" },

  // ღ
  { w: "ღვია", popularity: 5, aliases: [], note: "წიწვოვანი მარადმწვანე ბუჩქი" },
  { w: "ღოლო", popularity: 4, aliases: [], note: "ველური მწვანილი" },
  { w: "ღიღილო", popularity: 5, aliases: [], note: "მინდვრის ლამაზი ლურჯი ყვავილი" },
  { w: "ღვარძლი", popularity: 4, aliases: [], note: "სარეველა ბალახი" },
  { w: "ღორისქადა", popularity: 3, aliases: [], note: "ტყის ყვავილოვანი მცენარე" },
  { w: "ღომი", popularity: 4, aliases: [], note: "ქართული მარცვლეული კულტურა" },
  { w: "ღრიჭო", popularity: 3, aliases: [], note: "მცენარე" },

  // ყ
  { w: "ყაყაჩო", popularity: 5, aliases: [], note: "მინდვრის ცეცხლოვანი წითელი ყვავილი" },
  { w: "ყოჩივარდა", popularity: 5, aliases: [], note: "გაზაფხულის სათუთი ყვავილი" },
  { w: "ყურძენი", popularity: 5, aliases: [], note: "ვაზის ნაყოფი" },
  { w: "ყვითელი გვირილა", popularity: 4, aliases: [], note: "მინდვრის ყვავილი" },
  { w: "ყავის ხე", popularity: 5, aliases: ["ყავა"], note: "ტროპიკული მცენარე" },
  { w: "ყვითელყვავილა", popularity: 3, aliases: [], note: "მცენარე" },

  // შ
  { w: "შროშანი", popularity: 5, aliases: ["შროშანა"], note: "თეთრი სურნელოვანი ყვავილი" },
  { w: "შინდი", popularity: 5, aliases: [], note: "ხეხილოვანი ბუჩქი" },
  { w: "შოთხვი", popularity: 4, aliases: [], note: "ტყის ხე" },
  { w: "შაქრის ლერწამი", popularity: 5, aliases: [], note: "შაქროვანი მცენარე" },
  { w: "შავი ხე", popularity: 4, aliases: ["ებონოსი"], note: "ძვირფასი ხე" },
  { w: "შავთელა", popularity: 3, aliases: [], note: "ხე" },
  { w: "შავი მოცვი", popularity: 4, aliases: [], note: "კენკრა" },

  // ჩ
  { w: "ჩაი", popularity: 5, aliases: ["ჩაის ბუჩქი"], note: "სასმელი მცენარე" },
  { w: "ჩინური ვარდი", popularity: 4, aliases: ["ჰიბისკუსი"], note: "ოთახის ყვავილი" },
  { w: "ჩიტისთვალა", popularity: 4, aliases: [], note: "პატარა ცისფერი ყვავილი" },
  { w: "ჩიტისპურა", popularity: 3, aliases: [], note: "ველური ბალახი" },
  { w: "ჩიტიფეხა", popularity: 3, aliases: [], note: "მცენარე" },
  { w: "ჩიტისკუდა", popularity: 3, aliases: [], note: "ბალახი" },

  // ც
  { w: "ცაცხვი", popularity: 5, aliases: [], note: "თაფლოვანი სურნელოვანი ხე" },
  { w: "ციკლამენი", popularity: 4, aliases: ["ყოჩივარდა"], note: "ყვავილი" },
  { w: "ციტრუსი", popularity: 5, aliases: [], note: "მცენარეთა გვარი" },
  { w: "ცერცვი", popularity: 4, aliases: [], note: "პარკოსანი ბოსტნეული" },
  { w: "ცისთვალა", popularity: 4, aliases: [], note: "მინდვრის ყვავილი" },
  { w: "ცხენისწაბლა", popularity: 4, aliases: [], note: "დეკორატიული ხე" },
  { w: "ცისკარა", popularity: 3, aliases: [], note: "ყვავილი" },
  { w: "ცინერარია", popularity: 3, aliases: [], note: "დეკორატიული ყვავილი" },

  // ძ
  { w: "ძახველი", popularity: 4, aliases: [], note: "წითელნაყოფიანი ბუჩქი" },
  { w: "ძირტკბილა", popularity: 5, aliases: ["ლაკრიცა"], note: "სამკურნალო მცენარე" },
  { w: "ძაღლყურძენა", popularity: 4, aliases: [], note: "ტყის ბუჩქი" },
  { w: "ძეწნა", popularity: 4, aliases: ["მტირალა ტირიფი"], note: "ხე" },
  { w: "ძიძო", popularity: 3, aliases: [], note: "თაფლოვანი ბალახი" },
  { w: "ძაღლნიორა", popularity: 3, aliases: [], note: "ველური მცენარე" },

  // წ
  { w: "წიფელი", popularity: 5, aliases: [], note: "ტყის მძლავრი ხე" },
  { w: "წაბლი", popularity: 5, aliases: [], note: "ნაყოფიერი ტყის ხე" },
  { w: "წიწაკა", popularity: 5, aliases: [], note: "ბოსტნეული" },
  { w: "წითელი წიწაკა", popularity: 5, aliases: [], note: "ცხარე სანელებელი" },
  { w: "წიწმატი", popularity: 5, aliases: [], note: "მწვანილი" },
  { w: "წივანა", popularity: 3, aliases: [], note: "მარცვლოვანი ბალახი" },
  { w: "წითელი ხე", popularity: 4, aliases: ["მაჰაგონი"], note: "ძვირფასი ხე" },
  { w: "წითელთავა", popularity: 3, aliases: [], note: "სამყურას სახეობა" },

  // ჭ
  { w: "ჭინჭარი", popularity: 5, aliases: [], note: "მსუსხავი სამკურნალო მცენარე" },
  { w: "ჭადარი", popularity: 5, aliases: ["პლატანი"], note: "დიდრონი ქალაქური ხე" },
  { w: "ჭილი", popularity: 4, aliases: [], note: "ჭაობის მცენარე" },
  { w: "ჭინჭრაქა", popularity: 3, aliases: [], note: "მცენარე" },
  { w: "ჭაობის გვიმრა", popularity: 3, aliases: [], note: "მცენარე" },
  { w: "ჭანჭური", popularity: 4, aliases: ["ქლიავის სახეობა"], note: "ხეხილი" },

  // ხ
  { w: "ხორბალი", popularity: 5, aliases: [], note: "პურის თავთავიანი მარცვლეული" },
  { w: "ხახვი", popularity: 5, aliases: [], note: "ბოსტნეული" },
  { w: "ხურმა", popularity: 5, aliases: ["კარალიოკი"], note: "ნარინჯისფერი ხეხილი" },
  { w: "ხურტკმელი", popularity: 4, aliases: [], note: "ეკლიანი კენკროვანი ბუჩქი" },
  { w: "ხარისძირა", popularity: 4, aliases: [], note: "ზამთარში მოყვავილე სამკურნალო მცენარე" },
  { w: "ხავერდა", popularity: 4, aliases: ["ტაგეტესი"], note: "დეკორატიული ყვავილი" },
  { w: "ხავსი", popularity: 5, aliases: [], note: "ტყის სპოროვანი მცენარე" },

  // ჯ
  { w: "ჯანჯაფილი", popularity: 5, aliases: ["კოჭა", "იმბირი"], note: "სასარგებლო ფესვი" },
  { w: "ჯონჯოლი", popularity: 5, aliases: [], note: "ქართული საკონსერვო ბუჩქი" },
  { w: "ჯაგარი", popularity: 3, aliases: [], note: "მცენარეული ბოჭკო" },
  { w: "ჯეჯილი", popularity: 5, aliases: [], note: "ახლად ამოსული მწვანე პური" },
  { w: "ჯუჯა პალმა", popularity: 4, aliases: [], note: "მცენარე" },
  { w: "ჯადოსნური თხილი", popularity: 3, aliases: ["ჰამამელისი"], note: "ბუჩქი" },

  // ჰ
  { w: "ჰორტენზია", popularity: 5, aliases: [], note: "ულამაზესი ბაღის ყვავილი" },
  { w: "ჰიბისკუსი", popularity: 5, aliases: ["ჩინური ვარდი", "კარკადე"], note: "ყვავილი" },
  { w: "ჰიაცინტი", popularity: 4, aliases: [], note: "საგაზაფხულო ბოლქვიანი ყვავილი" },
  { w: "ჰამამელისი", popularity: 3, aliases: [], note: "სამკურნალო ბუჩქი" },
  { w: "ჰოსტა", popularity: 4, aliases: [], note: "ჩრდილის დეკორატიულფოთლოვანი მცენარე" },
  { w: "ჰელიოტროპი", popularity: 3, aliases: [], note: "ყვავილი" },
  { w: "ჰევეა", popularity: 4, aliases: ["კაუჩუკის ხე"], note: "ტროპიკული ხე" },
  { w: "ჰერბერა", popularity: 5, aliases: ["გერბერა"], note: "ფერადი ყვავილი" }
];
